### ISSUE TITLE
Feature Request: --platform windows

### ISSUE THREAD

**Issue by berwyn** [callstack/haul#104]
### Current Behavior
I use [React Native for Windows](https://github.com/Microsoft/react-native-windows) and would love if `--platform windows` was a thing I could use :)

### Expected Behavior
`--platform windows` runs and compiles code in my `.windows.tsx` files

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  0.2.1
| react-native     |  0.43.1
| node             | 7.7.1
| npm or yarn      | 0.21.3

**Comment by acoates-ms** [comment]
#418 should allow you to use RN for windows.
