### ISSUE TITLE
Support non image assets

### ISSUE THREAD

**Issue by satya164** [callstack/haul#120]
We should be able to package assets which are non-image. For example an HTML file for displaying in webview, a video etc. Figure out how packager deals with these and update `assetLoader` to support non-images.

**Comment by hiaw** [comment]
I pulled the `master` branch and tried out this feature with `m4v` files. It did not serve the file properly I think 

```
GET /assets/ios/App/Images/consent_01.m4v 404 175 - 7.264 ms
```

I get the feeling it should be serving from just `/App/Images/consent_01.m4v` instead?

**Comment by timwangdev** [comment]
Hi @satya164 ,
`<WebView source={require('./local/html')} />` loading raw text instead of html from package. Is this related to haul?
Thanks

**Comment by Krizzu** [comment]
@timwangdev 

I'd suggest to have a look at docs https://nodejs.org/api/modules.html#modules_file_modules.

Basically, node tries to resolve `html.js` file. You must explicitly add `.html` extension

**Comment by timwangdev** [comment]
Sorry, my typo, Fixed

**Comment by Krizzu** [comment]
In that case, have a look at `html-loader` - https://github.com/webpack-contrib/html-loader
