### ISSUE TITLE
Bad Error messages

### ISSUE THREAD

**Issue by shahen94** [callstack/haul#138]
### Current Behavior
it's giving non understandable error messages

`Helpful and easy to understand error messages` mentioned in readme, but it's no longer correct

<img width="372" alt="screen shot 2017-04-23 at 1 11 07 pm" src="https://cloud.githubusercontent.com/assets/13334788/25312267/5f2ec980-2826-11e7-833b-8d06afc2c786.png">

### Expected Behavior
Should show understandable error message, like it's showing rn-packager
<img width="373" alt="screen shot 2017-04-23 at 1 09 17 pm" src="https://cloud.githubusercontent.com/assets/13334788/25312258/2b5af41c-2826-11e7-80e3-6575baa83336.png">

### Haul Configuration (webpack.haul.js)
Configuration didn't changed

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  latest
| react-native     |  latest
| node             | 7.5.1
| npm or yarn      | 4.1.

**Comment by llaine** [comment]
Experiencing similar issue.

**Comment by GeeWee** [comment]
I feel like this would fix a lot of other issues that might be due to npm modules not being pre-transpiled, like #150  where the error message is not understandable.

I'm willing to give this a shot, if someone can point me in the right direction.

**Comment by grabbou** [comment]
@GeeWee let me know if you need any help, either here or on our Slack. Would love to see a support for better error messages.

**Comment by itaym2** [comment]
Hi, I was looking for issues which I can work on and came by this issue, though I couldn't reproduce it on latest. 
I then looked on the commits history and saw this PR: https://github.com/callstack/haul/pull/183
Did the above PR solved this issue?

**Comment by thymikee** [comment]
@itaym2 thanks for triaging this, closing then :)
