### ISSUE TITLE
Cannot find module 'core-js/modules/es7.string.pad-start'

### ISSUE THREAD

**Issue by shahen94** [callstack/haul#140]
### Current Behavior
<img width="856" alt="screen shot 2017-04-24 at 10 18 28 pm" src="https://cloud.githubusercontent.com/assets/13334788/25352203/3e39f3fa-293c-11e7-8a35-44a67f13f33a.png">

### Expected Behavior
init haul correctly

### Haul Configuration (webpack.haul.js)
can't generate configuration file

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  latest
| react-native     |  0.43.4
| node             | 7.5.0
| npm or yarn      | 4.5.0

**Comment by grabbou** [comment]
Have you tried removing your `node_modules` and installing them again?

**Comment by grabbou** [comment]
I just installed and inited project once again - had no issues at all. Let me know if the problem still persist - if yes, I'll be happy to reinvestigate this issue.

**Comment by Vlad-Zhukov** [comment]
The problem occurs when install deps with npm. Removing `node_modules` and reinstalling doesn't help. `yarn` works fine however.

What happens in my case is npm installs `react@16.0.0-alpha.12` -> `fbjs@0.8.12` -> `core-js@1.2.7` to the root of `node_modules`. There is no `module/es7.string.pad-start.js` in `core-js@1.2.7` yet.

Adding `core-js` to dev deps in my project fixed the problem.

**Comment by Genitana** [comment]
i    npm install core-js , and fixed it

**Comment by Traviskn** [comment]
I get this error when using npm instead of yarn. (npm version 4.2.0, node version 7.9.0)  Installing core-js as a dev dependency fixes the issue.

While yarn is great for many projects, I don't know that using yarn should be a requirement for using haul.  Would it make sense for core-js to be added as a peer dependency of this project to support npm users?

**Comment by Traviskn** [comment]
I still run into this issue on new projects when installing the latest version of haul, is there a reason this issue has been closed?

**Comment by satya164** [comment]
@Traviskn a pr adding `core-js` to haul's dependencies is welcome

**Comment by Traviskn** [comment]
sounds good, I'd be glad to help contribute
