### ISSUE TITLE
Building with `xcodebuild` Release configuration results in development build

### ISSUE THREAD

**Issue by joshuarh** [callstack/haul#167]
### Current Behavior

When I was using the default packager, the following command resulted in a production `.app` build:

`xcodebuild -project ios/MyProject.xcodeproj -scheme MyProject -configuration Release -destination 'name=iPhone 6s,OS=10.3' -derivedDataPath build | xcpretty`

This same command with `haul` results in a development (unminified) build. I'm not sure how to create a `.app` or `.ipa` file using the minified bundle created by `haul`.

(I am loading this `.app` file on to a simulator for automated testing.)

Once I'm ready to deploy, I'm also not sure how to tell my app to use `haul`'s bundle. Perhaps this could be addressed in documentation, or relevant documentation elsewhere linked to if it's obvious to folks more experienced with iOS than myself?

Thanks so much for creating this great tool. The React Native packager was driving me nuts. Please let me know if I missed something! 🌿

### Expected Behavior

Building with the `-configuration Release` flag should result in a production build.

### Your Environment

| software | version |
| --------- | ------- | 
| Haul             |  1.0.0-beta.0 |
| react-native     |  0.42.0 |
| node             | 7.4.0 |
| yarn      | 0.24.6 |

**Comment by grabbou** [comment]
This looks like a really severe bug. I am looking into it now. Will update this issue soon.

**Comment by thymikee** [comment]
@jukben can you have a look at triage this issue?

**Comment by jukben** [comment]
Last time I've inspected this everything working fine. [This is the part of RN responsible for it]( https://github.com/facebook/react-native/blob/master/scripts/react-native-xcode.sh#L116). It should run `haul bundle` which produce production bundle.

You can also check the what's happening under the hood in logs.
![image 1](https://user-images.githubusercontent.com/8135252/33560971-8dcce92e-d911-11e7-8dcc-f54b1f84ba6a.jpg)
