### ISSUE TITLE
Would you add bundle split feature?

### ISSUE THREAD

**Issue by xiaoDC** [callstack/haul#173]
Hi, would you implement the bundle split feature?
something like [https://github.com/facebook/react-native/pull/10804](url)

**Comment by iamawebgeek** [comment]
+1 @xiaoDC  have you found any solution for this?

**Comment by xiaoDC** [comment]
@iamawebgeek i give up `haul`, and i use the package `rn-packager`

**Comment by thymikee** [comment]
Closing in favor of https://github.com/callstack/haul/issues/70
