### ISSUE TITLE
Android build APK breaking on config

### ISSUE THREAD

**Issue by brendanscarano** [callstack/haul#186]
I'm attempting to run `./gradlew assembleRelease` in the android directory of my react-native app to build the APK. I expect the following code to replace my config files across the app however it's not resolving properly.

webpack.haul.js
```
const path = require("path");

module.exports = ({ platform, root }, defaults) => ({
  entry: `./index.${platform}.js`,
  resolve: {
      ...defaults.resolve,
      alias: {
          ...defaults.resolve.alias,
          config: path.join(root, 'config')
      }
  }
});
```

App.js
```
import React from 'react';
import {Text, View} from 'react-native';
import config from 'config';

// more code below...
```
When I run I get the following error:
```
Unable to resolve module `config` from `/Users/brendan/Projects/<project-name>/App.js`: Module does not exist in the module map or in these directories:
  /Users/brendan/Projects/<project-name>/node_modules
````

It seems to be working fine for the iOS build however for Android this issue is being thrown.

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  ^1.0.0-beta.1
| react-native     |  ^0.44.0
| node             | v8.0.0
| yarn      | 0.21.3

**Comment by satya164** [comment]
Did you follow the instructions here to setup the build? https://github.com/callstack-io/haul#getting-started

**Comment by brendanscarano** [comment]
@satya164 yes, I followed the documentation and added 
```
project.ext.react = [
    cliPath: "node_modules/haul/bin/cli.js"
]
```
to my android/app/build.gradle file

When I run `yarn run haul start -- --platform android` from my project directory it seems to build fine, it's only when I run `./gradlew assembleRelease` that I get the breaking error.

**Comment by satya164** [comment]
What's your React Native version? Do you have source code which I can look at?

**Comment by brendanscarano** [comment]
RN version ^0.44.0
And source code for which files?

**Comment by brendanscarano** [comment]
It seems that if follow the documentation and add
` project.ext.react = [
    cliPath: "node_modules/haul/bin/cli.js"
 ]
`
to my `android/app/build.gradle` but comment out `apply from: "../../node_modules/react-native/react.gradle"` below it, I'm able to run the app locally as well as build the apk file with the `./gradlew assemblyRelease` command

**Comment by satya164** [comment]
Can you post a full example so we can debug it?

**Comment by Krizzu** [comment]
Hey @brendanscarano 
Did You manage to solve the issue?

**Comment by Ble3k** [comment]
I had the same problem and solved it just by adding
```project.ext.react = [ cliPath: "node_modules/haul/bin/cli.js" ]```
as it said in docs.

**Comment by jurby** [comment]
I had the same problem and solved it just by adding:
`// Haul
project.ext.react = [
    root: "../../",
    cliPath: "node_modules/haul/bin/cli.js"
]`
