### ISSUE TITLE
Figure out way to configure Haul for advanced use-cases

### ISSUE THREAD

**Issue by grabbou** [callstack/haul#195]
Like adding a platform. Potentially, we can add named exports for `webpack.haul.js` config or a different file.

Also, consider adding another file (e.g. `config.haul.js`) so that is no longer confusing.

**Comment by grabbou** [comment]
cc: @skellock do you guys have any use-cases like that or would have some ideas?
cc: @rozele interested to hear how you utilise CLI config in rn-windows so we can make sure it's also compatible here

**Comment by skellock** [comment]
Some of the crew here at Infinite Red are doing some work on the win 7 port. Their needs would be similar to Eric's.

Might be worth reaching out to @ptmt and @dlowder-salesforce too.  I'm sure they have packager battle scars.

**Comment by zamotany** [comment]
See #323
