### ISSUE TITLE
In mode `all`, progress indicator is broken

### ISSUE THREAD

**Issue by grabbou** [callstack/haul#208]
Progress indicator is receiving two, mutually exclusive, progress events, one from iOS compiler and second, from Android compiler.

We should build a nice proxy / abstraction that will collect all events from compilers and report a summary.

**Comment by zamotany** [comment]
Might be helpful:
https://github.com/TrueCar/gluestick/blob/next/packages/gluestick/src/config/webpack/progressHandler.js
