### ISSUE TITLE
Circle CI node 4 container is always failing when installing dependencies

### ISSUE THREAD

**Issue by zamotany** [callstack/haul#212]
On my branch `feature/hmr` node 4 container is always failing when installing dependencies:
```
node v4.8.4
npm ERR! npm  v2.15.11
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package babel-preset-react-native@1.9.2 does not satisfy its siblings' peerDependencies requirements!
```

You can see the full output here: https://circleci.com/gh/callstack-io/haul/407

What's really interesting is that I **don't have version 1.9.2 of `babel-preset-react-native` as a peer dependency** but `^2.0.0`.
Here yout can see my `package.json`: https://github.com/callstack-io/haul/blob/9f7e65300c8a2c2b5b5bf2eb9d3263b0aed7a0ee/package.json#L25-L28

As a workaround, I need to _rebuild without cache_ and then it passes, but it's really annoying.

**Comment by thymikee** [comment]
Also, Haul is pretty buggy on Node 4, e.g. running `bundle` or `start --platform android` throws compilation errors.

**Comment by satya164** [comment]
We should switch to npm@3 on Node 4 and try. We don't support npm@2 anyway.
