### ISSUE TITLE
Debug JS remotely with typecript

### ISSUE THREAD

**Issue by EamonnLaffey** [callstack/haul#215]
### Current Behavior
Remote JS debugging does not work with typescript and haul version 1.0.0-beta.4. When you try and debug js remotely the following error is thrown: `Cannot read property 'BlobBuilder' of undefined`

### Expected Behavior
Currently downgrading to version 1.0.0-beta.2 of haul allows the JS to be remotely debugged version 1.0.0-beta.4 of haul should behave the same.

### Haul Configuration (webpack.haul.js)
I am using the typescript configuration that allows synthetic imports which can be found here: https://github.com/callstack-io/haul/blob/master/docs/Recipes.md#typescript

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-beta.4
| react-native     |  0.47.1
| node             | 8.1.4
| yarn      | 0.27.5

**Comment by yenbekbay** [comment]
In my case this was caused by the [socket.io-client](https://github.com/socketio/socket.io-client) dependency bundled with [Reactotron](https://github.com/infinitered/reactotron/). Removing Reactotron fixed the issue.

**Comment by Traviskn** [comment]
I'm getting this error (`Cannot read property 'BlobBuilder' of undefined`) when trying to launch the remote debugger while using haul and reactotron in conjunction.  Granted, reactotron still works fine so in most cases I don't _need_ the remote debugger, but it's still quite strange

**Comment by skellock** [comment]
I think it has something to do with [the way i load `socket.io`](https://github.com/infinitered/reactotron/blob/cf39170200880550e9038ec79b29fb960cb8294c/packages/reactotron-react-native/src/index.js#L9).

Loading it with `var io = require('socket.io-client')` might be a fix.

I guess the execution environment of javascript is different while chrome debugging, so I think `BlobBuilder` needs to be handled differently.  This may be what loading `socket.io-client` directly does.

What I type into my editor and what runs is pretty far apart these days.  😸 

In v2 we ended up removing `socket.io` entirely from Reactotron.  A little websocket-ery does the trick just fine.

If you do pin it down, lemme know tho (either here or over on [our repo](https://github.com/infinitered/reactotron/issues)).

**Comment by Traviskn** [comment]
@skellock I'll be looking forward to v2 then!  We actually just today updated to v1.13.2 and remote debugging seems to be working again 🎉

**Comment by apexskier** [comment]
Is this closable? Our project uses Typescript and we've had debugging working on the last several versions.
