### ISSUE TITLE
Double R in Chrome Debugger should reload the app

### ISSUE THREAD

**Issue by satya164** [callstack/haul#218]

**Comment by jhen0409** [comment]
I may could help this, I've do similar thing in [`react-native-debugger`](https://github.com/jhen0409/react-native-debugger/blob/master/app/worker/devMenu.js#L8), it take `DevSettings.reload` to make it possible, but currently it doesn't support Android.

**Comment by satya164** [comment]
I was thinking that maybe we could hijack the way live reload is implemented.

**Comment by grabbou** [comment]
Already implemented, but with a button.
