### ISSUE TITLE
Can't use modified .babelrc 

### ISSUE THREAD

**Issue by blackxored** [callstack/haul#231]
This is part of lerna setup so I'm assuming some of the issues might have to do with that. It seems if we add a .`babelrc` (even the default with the react-native preset) EmitterSubmission fails to resolve. Any clues?

**Comment by grabbou** [comment]
Haven't had issues using custom `babelrc` so far -> https://github.com/callstack-io/haul/blob/master/src/utils/getBabelConfig.js#L18

Can you post a more detailed explanation of a problem including error message and stack trace you are receiving?

**Comment by blackxored** [comment]
Yes I’ve been through this file. The problem is it doesn’t seem to apply
the later stages (fixRequires, etc) if I put a babelrc in the nested
folder. It says EmissionSubscription is not a function.

-- 
Best Regards,

Adrian Perez
https://adrianperez.codes

**Comment by grabbou** [comment]
I guess the problem is that we only take `babelrc` from within the "cwd" you run `haul start` - not take nested babel configs into account.

**Comment by blackxored** [comment]
Yes. Haul lives under a nested dir, if I add a babelrc to that nested dir
is even errors staring popping out.

-- 
Best Regards,

Adrian Perez
https://adrianperez.codes

**Comment by zamotany** [comment]
Would recursive search for `.babelrc` in parent directories solve your problem?

**Comment by blackxored** [comment]
I think it should work like (to my understanding), babel does. With recursive and traverse up search of compile settings.

**Comment by zamotany** [comment]
Could describe your project structure? I'm particularly interested in where haul is installed and where `.babelrc` files resides. Also from where are you running haul - from monorepo directory or some somewhere else?

**Comment by blackxored** [comment]
```
.
├── android
│   ├── app
│   │   └── src
│   ├── gradle
│   │   └── wrapper
│   └── keystores
├── core
│   ├── __tests__
│   │   └── __snapshots__
│   ├── app
│   │   └── __tests__
│   ├── auth
│   │   └── __tests__
│   ├── config
│   │   └── __tests__
│   ├── device
│   │   └── __tests__
│   ├── navigation
│   ├── settings
│   │   └── __tests__
│   ├── types
│   ├── ui
│   │   └── __tests__
│   └── viewer
│       └── __tests__
├── coverage
│   └── lcov-report
│       └── esk
├── docs
├── flow-typed
│   └── npm
│       └── @commitlint
├── ios
│   ├── ESK
│   │   ├── Base.lproj
│   │   └── Images.xcassets
│   ├── ESK-tvOS
│   ├── ESK-tvOSTests
│   ├── ESK.xcodeproj
│   │   ├── project.xcworkspace
│   │   ├── xcshareddata
│   │   └── xcuserdata
│   ├── ESKTests
│   └── build
│       ├── Build
│       ├── Logs
│       └── ModuleCache
├── libs
│   ├── payments
│   └── search
├── platforms
│   ├── native
│   │   ├── auth
│   │   ├── components
│   │   ├── device
│   │   ├── login
│   │   ├── navigation
│   │   └── profile
│   ├── server
│   │   ├── auth
│   │   ├── data
│   │   └── dist
│   └── web
└── services
    └── auth
        └── lib

66 directories
```

`.babelrc` is at the project's root.
