### ISSUE TITLE
Deprecate `haul-integrate.sh`

### ISSUE THREAD

**Issue by grabbou** [callstack/haul#234]
There's CLI_PATH available: https://github.com/facebook/react-native/commit/dcecfa3189d7a71f57f908cc008e26c20a7cb2f5 for quite a few versions.

**Comment by keplersj** [comment]
I was able successfully remove the Haul Integrate build phase and make use of this environment variable by changing the `Bundle React Native code and images` Build Phase script to:

```
export NODE_BINARY=node
export CLI_PATH=node_modules/haul/bin/cli.js
../node_modules/react-native/scripts/react-native-xcode.sh
```
