### ISSUE TITLE
Babel is compiling all node_modules

### ISSUE THREAD

**Issue by jaredru** [callstack/haul#261]
### Current Behavior
With #242, the babel/happypack-loader `exclude` attribute was removed. Previously, the attribute was set as `exclude: /node_modules\/(?!react|@expo|pretty-format|haul)/`.

I imagine this might cause a few issues, but the one we're hitting is that [art](https://github.com/sebmarkbage/art) (a dependency of `react-native`) is getting compiled by Babel and breaking, because it is not built as an ES6 module. In particular, https://github.com/sebmarkbage/art/blob/51ffce8164a555d652843241c2fdda52e186cbbd/core/color.js#L196 is being transformed to `if (undefined.hex == null) undefined.hex = Color.hex;`, as `this` is `undefined` in an ES6 module.

### Expected Behavior
Don't transpile `node_modules`, except for the few relevant modules.

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-beta.7
| react-native     |  0.49.3
| node             | 8.7.0
| yarn      | 1.2.1

**Comment by satya164** [comment]
cc @zamotany

**Comment by Krizzu** [comment]
Maybe adding `exclude` [in `babel-loader` rule would fix this issue?](https://github.com/callstack/haul/blob/master/src/utils/makeReactNativeConfig.js#L92)

**Comment by grabbou** [comment]
Thanks for reporting, that is indeed our mistake - unintended DEV change has slipped through review process. I am reverting that line back, releasing new version and we will work on a better way later.

**Comment by Titozzz** [comment]
Hello, can you release the beta 8 to npm ?
Thanks
