### ISSUE TITLE
Failed to compile without any reason

### ISSUE THREAD

**Issue by xareelee** [callstack/haul#262]
### Current Behavior

I just install haul and initialize the project:

```
$ yarn add --dev haul
$ yarn run haul init
```

After running `haul bundle` command, the process was terminated without any error message.

```
$ ./node_modules/.bin/haul bundle --platform ios --dev false --bundle-output ios/jsbundle/main.jsbundle --assets-dest ios/jsbundle

 INFO  Haul is now bundling your React Native app in production mode.

Starting from:

iOS        [====================] 100%



 ERROR  Failed to compile
error Command failed with exit code 1.
```

I have no clue to fix this issue.

### Expected Behavior

Succeed or show the reason for the error.

### Haul Configuration (webpack.haul.js)

```js
const path = require('path');

module.exports = ({ platform }) => ({
  entry: `./index.js`,
  resolve: {
    modules: [
      path.resolve('./packages'),
      path.resolve('../../packages'),
      path.resolve('./node_modules'),
    ],
  },
});
```

### Your Environment

`

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-beta.7
| react-native     |  0.49.3
| node             |  8.3.0
| npm or yarn      | npm 5.4.1 & yarn 0.28.4

**Comment by Krizzu** [comment]
@xareelee Hey, thanks for filling this issue. For the first look, it seems like you forgot to extend your config with Haul's default config.

[Please checkout these docs about configuring Haul.](https://github.com/callstack/haul/blob/master/docs/Configuration.md)

**Comment by thymikee** [comment]
We should pass the actual error stack alongside the `Failed to compile` message.

**Comment by jukben** [comment]
It sounds pretty straightforward I could make a PR for it if no one is interested in it. 👍

**Comment by Titozzz** [comment]
We need this on warnings too 😢

**Comment by jukben** [comment]
@Titozzz Could you please share some example? Configuration? Whatever helps to reproduce it?

From what I know, warnings should be already implemented: 
https://github.com/callstack/haul/blob/master/src/messages/bundleBuilt.js#L24

**Comment by jukben** [comment]
@Titozzz Good catch, we should list *what* warnings exactly happened. I've created issue for it https://github.com/callstack/haul/issues/274
