### ISSUE TITLE
Couldn't load bundle with default configuration running on react 0.49.3

### ISSUE THREAD

**Issue by dstollie** [callstack/haul#268]
Just ran the default steps to replace the default react native packager with haul. Everything went smoothly but after running the app in the simulator I get this error.

Running haul as: `yarn run haul start -- --platform ios`

####  Error in the simulator
![screen shot 2017-11-01 at 00 26 05](https://user-images.githubusercontent.com/7110155/32253440-47143284-be9b-11e7-8b97-90a156c672c3.jpg)

#### Error in the terminal

![screen shot 2017-11-01 at 00 27 15](https://user-images.githubusercontent.com/7110155/32253487-78efe4d8-be9b-11e7-94d3-d28250ec069d.jpg)

When going back the the normal packager by running `react-native start` everything work as expected.

### Your Environment
Running on osx testing in a simulator

| software         | version
| ---------------- | -------
| Haul             |  v0.21.3
| react-native     |  0.49.3
| node             | 8.5.0
| npm or yarn      | yarn

**Comment by Krizzu** [comment]
Hey @dstollie, thanks for your input.
Can you tell me, what's the name of your entry file?

**Comment by dstollie** [comment]
If you mean with my the `index.ios.js` it is located in the root folder, the same place as where `webpack.haul.js` file and the `ios` folder are located

**Comment by Krizzu** [comment]
Can you change the name of that file to `index.js` and tell me if it finds the bundle?

**Comment by GitHubTracey** [comment]
Hi @Krizzu, 

I experienced the same error:
software | version
Haul | v1.0.0-beta.7
react-native | 0.50.0
node | 8.2.1
npm or yarn | same for both npm and yarn

scripts pertinent to what we are doing... :
    "dev:ios": "concurrently \"npm run haul -- --platform ios\" \"react-native run-ios\"",
    "bundle:ios": "node node_modules/.bin/haul bundle --entry-file='index.ios.js' --bundle-output='./ios/myapp/main.jsbundle' --dev=false --platform='ios' --assets-dest='./ios'",
(we have some config for sentry in each of the .ios.js and .android.js) Having moved both into a single index.js file with a selection for Platform.OS did not change the result.

I downgraded react-native to 0.49.0 and had the same result. 

In the end, we needed to downgrade react-native to 0.48.0 to get haul to work without the same message that @dstollie experienced. Happy to try a few things later if you have any ideas.

Cheers!

**Comment by keplersj** [comment]
Just encountered this. Same issue as #251

**Comment by Krizzu** [comment]
@keplersj @GitHubTracey @dstollie 
I hope this issue is fixed with #276

**Comment by GitHubTracey** [comment]
@Krizzu thanks for having replied... I didn't actually see the notification for your reply otherwise I would have definitely tried again. Sorry for a very very very late reply 😆

**Comment by Krizzu** [comment]
@GitHubTracey Welcome to the future 🤖

You're welcome!
