### ISSUE TITLE
Setting ref in function (pure) component

### ISSUE THREAD

**Issue by junkycoder** [callstack/haul#271]
Hi guys,

I found Haul as good alternative to RN packager, but I run into:

![simulator screen shot - iphone 6 - 2017-11-02 at 18 32 28](https://user-images.githubusercontent.com/1243903/32340909-3881c742-bffc-11e7-850a-ee83356cc658.png)

and here is the component:

<img width="744" alt="snimek obrazovky 2017-11-02 v 18 28 16" src="https://user-images.githubusercontent.com/1243903/32340704-a9e0cbb4-bffb-11e7-8783-49002c9535b7.png">

Any idea, why this is ok with RN packager but not with Haul?

react-native-cli: 2.0.1
react-native: 0.49.5
yarn: v0.22.0
haul: 1.0.0-beta.7

PS: I'd love to switch to Haul because, you know RN packager is too slow :)

**Comment by Krizzu** [comment]
Hey @junkycoder 
This is not `Haul` related, rather `React` related.

[See docs about ref here](https://reactjs.org/docs/refs-and-the-dom#refs-and-functional-components)

**Comment by junkycoder** [comment]
@Krizzu Ohh, thanks. I was just curious why this works before i switched to Haul. Now I got it. Thx :)
