### ISSUE TITLE
Recipe breaks on unexpected token

### ISSUE THREAD

**Issue by alper** [callstack/haul#272]
I'm doing the recipe as it is here to get my react-native ts project to work.
https://github.com/callstack/haul/blob/master/docs/Recipes.md

It then gives me:

```
   SyntaxError: /Users/alper/Documents/iOS-App/rn/webpack.haul.js: Unexpected token (4:4)
  2 |   entry: `./index.js`,
 3 |   module: {
> 4 |     ...module,
   |     ^
 5 |     rules: [
 6 |       {
 7 |         test: /\.tsx?$/,
```

Is it dying on the spread operator? 

| software         | version
| ---------------- | -------
| Haul             |  haul@1.0.0-beta.7
| react-native     |  react-native@0.49.5
| node             | v8.9.0
| npm or yarn      | yarn 1.3.2

Full haul.js:

```
module.exports = ({ platform }, { module, resolve }) => ({
  entry: `./index.js`,
  module: {
    ...module,
    rules: [
      {
        test: /\.tsx?$/,
        exclude: '/node_modules/',
        use: [
          {
            loader: 'babel-loader',
          },
          {
            loader: 'ts-loader'
          },
        ],
      },
      ...module.rules
    ]
  },
  resolve: {
    ...resolve,
    extensions: [
      '.ts',
      '.tsx',
      `.${platform}.ts`,
      '.native.ts',
      `.${platform}.tsx`,
      '.native.tsx',
      ...resolve.extensions],
  },
});
```

**Comment by keplersj** [comment]
I experienced the same thing and just rewrote the section using `Object.assign()`:

```js
module.exports = ({ platform }, { module, resolve }) => ({
  entry: `./index.js`,
  module: Object.assign({}, module, {
    rules: [
      {
        test: /\.tsx?$/,
        exclude: '/node_modules/',
        use: [
          {
            loader: 'babel-loader',
          },
          {
            loader: 'ts-loader'
          },
        ],
      },
      ...module.rules
    ]
  }),
  resolve: Object.assign({}, resolve, {
    extensions: [
      '.ts',
      '.tsx',
      `.${platform}.ts`,
      '.native.ts',
      `.${platform}.tsx`,
      '.native.tsx',
      ...resolve.extensions],
  })
});
```

**Comment by Krizzu** [comment]
@GeeWee Any thoughts about it?

**Comment by GeeWee** [comment]
That's strange - looking at the [node compat table](http://node.green/#ESNEXT-candidate--stage-3--object-rest-spread-properties) the node versions should easily be able to spread the module object. I'm a little puzzled - haul just uses the global node version right?

**Comment by thymikee** [comment]
@satya164 had the idea to not use external babelrc files, so things like that should not happen. @zamotany will work on adjusting our `babel-register` flow

**Comment by mixedCase** [comment]
I believe I have found the cause. Removing babel-loader in modules.rules.use triggers it, adding it back fixes it; even if I wasn't using synthetic imports. Use of spread operator/Object.assign in the webpack config has no impact, @keplersj reflects this, since the spread operator is still being used for module.rules and resolve.extensions in the snippet he posted.

@alper Do you remember wether you installed babel-loader as a dependency before or after posting this issue?

**Comment by zamotany** [comment]
@thymikee `babel-register` _flow_ looks fine to me. That being said I also had this issue couple of times, but usually it was gone after few Haul restarts, so I'm not aware what was the cause.
