### ISSUE TITLE
Lottie + Haul dosn't work while remote debug is on

### ISSUE THREAD

**Issue by jukben** [callstack/haul#278]
The problem is related to [Lottie](https://github.com/airbnb/lottie-ios)

### Current Behavior
When you start to debug remotely it fails with an error `Cannot create property 'runCommand' on string 'LottieAnimationView'`

### Expected Behavior
Debug remotely should be possible

### Haul Configuration (webpack.haul.js)
```js
module.exports = ({ platform }) => ({
  entry: `./index.${platform}.js`,
})
```
| software         | version
| ---------------- | -------
| Haul             |  v1.0.0-beta.9
| react-native     |  0.49.3
| node             | v8.6.0
| npm or yarn      | 1.2.1
| lottie-react-native | 2.2.7

**Comment by chelovekdrakon** [comment]
@jukben what is the solution for this? I've just upgraded haul from 1.0.0-rc15 to 0.13.1 and run into this error.
@satya164 could you help me with this?

**Comment by chelovekdrakon** [comment]
In `NativeSafeComponent.js` on componnet `LottieAnimationView` code try to set `runCommand` property

**Comment by chelovekdrakon** [comment]
@zamotany Aloha! 
Here is a sample project with a repro of the issue: https://github.com/chelovekdrakon/lottie-issue

**Comment by zamotany** [comment]
Temporary workaround:
1. Install `remove-strict-webpack-plugin`
2. Add this plugin to the Webpack config like so:
```js
import {withPolyfills, makeConfig} from '@haul-bundler/preset-0.60';
import RemoveStrict from 'remove-strict-webpack-plugin';

export default makeConfig({
  bundles: {
    index: {
      entry: withPolyfills('./index'),
      transform({config}) {
        config.plugins.push(new RemoveStrict());
      },
    },
  },
});
```
(Don't worry about the errors, it works fine).

Use this workaround until the proper fix lands.

**Comment by chelovekdrakon** [comment]
@zamotany thank you for fixing it!
How should we use it now instead of `config.plugins.push(new RemoveStrict());` ?

**Comment by zamotany** [comment]
@chelovekdrakon 
There's a `looseMode` property in configuration now: https://github.com/callstack/haul/blob/master/docs/Configuration.md
Here's a recipe:
https://github.com/callstack/haul/blob/master/docs/Recipes.md#using-with-lottie-or-loose-mode-only-compatible-libraries
