### ISSUE TITLE
polyfill is not complete

### ISSUE THREAD

**Issue by bakso** [callstack/haul#284]
As the screenshot below:
![image](https://user-images.githubusercontent.com/659130/32842076-c33208a4-c9e1-11e7-88d1-b28249c45c51.png)

There is not Symbol and many other polyfills,  which exist in the core-js .
I wander what will the strategy of haul be? Because we are still use 0.41.2, the Android side's jscore engine is really old and need many polyfills.
And now what is the best means to handle this?

**Comment by satya164** [comment]
`core-js` is not included as it is heavy, can affect performance and decrease startup time. You can include your own polyfills as you need them.
