### ISSUE TITLE
Use workers to generate bundle

### ISSUE THREAD

**Issue by Krizzu** [callstack/haul#287]
Haul - Use worker to generate webpack bundle.

## How Haul works now
Once you start Haul, you're asked to specify if you're going to handle one or both platforms. In latter case, we're using Webpack's multi compiler mode.  To serve a bundle, we have to wait for both (or maybe more) compilations to finish. This equals to increased waiting time for bundle and possible block for future platform expanding.
Additionally, [we have to handle cases,](https://github.com/callstack/haul/blob/master/src/utils/makeReactNativeConfig.js#L211) [ where webpack config is an array](https://github.com/callstack/haul/blob/master/src/commands/start.js#L62-L64), [instead doing it in generic way.](https://github.com/callstack/haul/blob/master/src/commands/start.js#L91)

## What's wrong with this approach?
As mentioned, expanding such cases is hard, as you have to keep in mind few edge cases. We could make this part easier by handling webpack in more generic way.

## Proposal
I propose a solution: a custom express middleware, that'll mimic [webpack dev middleware](https://github.com/webpack/webpack-dev-middleware), but instead of running it in the same process as our server, we spawn a process with webpack, tell him where to find necessary data and serve just the output from it. 

With this approach, we can drop the need for handling multi-compiler case and allow us to fix/enhance Haul with generic mindset and serve files ON DEMAND.

## Details - WIP

Here I'll keep some tech and non-tech details, maybe for future development.

#### Pros
1. Generic mindset when building configs/other features
2. Bundling on demand - only specific request will trigger Webpack spawning and serving
3. Faster express starting
4. Never serve the wrong bundle*

#### Cons
1. We'll have to refactor major parts of Haul
2. Communication between fork and parent can only be with serializable objects

### Code

You can track the progress at #291. At the current stage, it's ready to check out (creates and sends bundle).

**Comment by thymikee** [comment]
I'll just leave this package here, maybe useful, maybe not: [jest-worker](https://github.com/facebook/jest/tree/master/packages/jest-worker)

**Comment by zamotany** [comment]
Will this allow to toggling compilations? Like let's say when we will have some interactive CLI, will this allow us to toggle compilation when haul is already running?

**Comment by Krizzu** [comment]
There will be no compilations toggling, but compilation on demand - say, android bundle is requested. Middleware checks if it has forked webpack for android before. If no, spawn it and send bundle. Otherwise send a bundle.

**Comment by thymikee** [comment]
Closed via https://github.com/callstack/haul/pull/339
