### ISSUE TITLE
How ESLint resolve webpack aliases

### ISSUE THREAD

**Issue by jurajkrivda** [callstack/haul#301]
Hi,
my webpack config

```
const path = require('path');

module.exports = ({ root, platform, output }, defaults) => ({
  entry: './index.js',
  output: {
    ...output,
    filename: `index.${platform}.bundle`,
  },
  resolve: {
    ...defaults.resolve,
    alias: {
      ...defaults.resolve.alias,
      styles: path.join(root, 'src', 'styles'),
      ui: path.join(root, 'src', 'components', 'UI'),
    },
  },
});
```

When I import styles eg `import { AppColors } from 'styles';` it works but ESLint shows me this: `[eslint] 'styles' should be listed in the project's dependencies. Run 'npm i -S styles' to add it (import/no-extraneous-dependencies)`. How could I resolve aliases?

My eslintrc

```
const path = require('path');

module.exports = {
  extends: 'dacz',
  rules: {
    'no-console': 0,
    'no-alert': 0,
    'react/prefer-stateless-function': 0,
  },
  settings: {
    'import/resolver': {
      webpack: 'webpack.haul.js',
    },
  },
};
```

**Comment by Krizzu** [comment]
Hey @jurajkrivda 
This problem comes not from Haul/webpack, but rather your eslint config. Please check "import/no-unresolved" rule, either disable it or add `ignore` property to include your aliases

**Comment by Krizzu** [comment]
Related: #302

**Comment by jukben** [comment]
Hi @jurajkrivda 

Currently, it's not possible to use `eslint-plugin-import` together with Haul. Anyway, I've created issue for it so I hope that we fix this behavior in near future.
https://github.com/callstack/haul/issues/302

**Comment by AleksandrZhukov** [comment]
Hi @jurajkrivda 
Can you explain the solution for this issue?
