### ISSUE TITLE
Can HMR auto open like origin react-native packager

### ISSUE THREAD

**Issue by bakso** [callstack/haul#304]
React-native 's origin packager doesn't need config to enabled HMR like the doc below:
https://github.com/callstack/haul/blob/master/docs/hmr/Setup.md#automatic-setup

And also origin packager has not requirement of special attention(like root component must export default ...).

What comes the diffrences?

**Comment by zamotany** [comment]
Different solutions (custom metro bundler implementation vs webpack HMR API + react-hot-loader).
https://webpack.js.org/concepts/hot-module-replacement/
https://github.com/gaearon/react-hot-loader
https://blog.callstack.io/react-native-webpack-hmr-%EF%B8%8F-a4c2bf76fba
