### ISSUE TITLE
building hangs on while processing too large files

### ISSUE THREAD

**Issue by bbodi** [callstack/haul#307]
### Current Behavior
haul "Building" process hangs on if I want to bundle too large (37k lines) javascript files. I wanted to try Kotlin with react-native and include its runtime library as a dependency, but haul has problem bundling it.

### Expected Behavior
The processing should end successfully in reasonable time.

### Haul Configuration (webpack.haul.js)
```javascript
module.exports = ({ platform }) => ({
  entry: `./index.js`,
});
```

### Your Environment
Environment:
  OS: Windows 10
  Node: 6.10.2
  Yarn: 1.3.2
  npm: 3.10.10
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4408382

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.4 => 0.50.4

### Steps to reproduce
1. ``react-native init project``
2. ``cd project``
3. install the kotlin runtime library ``npm install --save kotlin``
4. ``yarn add --dev haul``
5. ``yarn haul init``
6. modify index.js like
```js
import { AppRegistry } from 'react-native';
import App from './App';
import Kotlin from 'kotlin'; // this is the added line

AppRegistry.registerComponent('project', () => App);
```
7. ``yarn haul start -- --platform android``

**Comment by zamotany** [comment]
With those steps, I cannot reproduce the issue. It's building fine for me.

**Comment by bbodi** [comment]
Thanks for your feedback.

I tried it again, and now it works also for me.

So this issue is solved.
Thanks.
