### ISSUE TITLE
Error on new project

### ISSUE THREAD

**Issue by iRoachie** [callstack/haul#308]
### Current Behavior

On creating a new project with haul the app shows error screen on launch

#### Steps to reproduce
* Create new react-native project (react-native init)
* Add haul `yarn add --dev haul`
* Start haul server `yarn run haul`
* Run the app in the iOS simulator `react-native run-ios`

### Expected Behavior

The app should run

### Haul Configuration (webpack.haul.js)

```js
module.exports = ({ platform }) => ({
  entry: `./index.js`,
});
```

### Your Environment

Mac OS High Sierra, iOS 11.1 simulator iPhone 6

| software         | version
| ---------------- | -------
| Haul             |  ^1.0.0-beta.10
| react-native     |  0.50.4
| node             | 8.7.0
| npm or yarn      | yarn 1.3.2, npm 5.4.2

**Comment by Krizzu** [comment]
Hey @iRoachie 
Could You please tell me what error you get?
Have you run `Haul init` before `Haul start`?

**Comment by iRoachie** [comment]
Sure. Yea I did.

![simulator screen shot - iphone 6 - 2017-12-01 at 06 21 55](https://user-images.githubusercontent.com/5962998/33478525-f431ca18-d65f-11e7-8a2d-d0a09ee92970.png)

**Comment by jurajkrivda** [comment]
I can confirm this error in RN 0.49

**Comment by jukben** [comment]
This is a bug related to Webpack. I'm still searching for a satisfactory solution. As a walk around you have to downgrade to Webpack 3.8.x.

This is related PR into Webpack itself: https://github.com/webpack/webpack/pull/5862

**Comment by jukben** [comment]
Another walk around for this is just open dev tools to enforce "webworker" environment. 💪

**Comment by thymikee** [comment]
I'll close it, but we need a proper fix, and release soon.

**Comment by SEAPUNK** [comment]
you can just pin to an older version of webpack for now
