### ISSUE TITLE
Hot reload refreshes entire app

### ISSUE THREAD

**Issue by stief510** [callstack/haul#311]
### Current Behavior
I implemented HMR but when I make any change to a component the entire app refreshes. My app is setup by `index.tsx` importing the app from `app.tsx`. Therefore, I had to do the manual set up. 

```
import app from './app/app';

AppRegistry.registerComponent('mobile', makeHot(() => app));

if ((module as any).hot) {
  (module as any).hot.accept(() => {});
  (module as any).hot.accept('./app/app', () => {
    clearCacheFor(require.resolve('./app/app'));
    redraw(() => require('./app/app').default);
  });
}
```

Am I missing something? Thanks

### Expected Behavior
It should just replace that one file and not the entire app refresh

### Haul Configuration (webpack.haul.js)
```
module.exports = ({ platform }, { module, resolve }) => ({
  entry: `./index.tsx`,
  module: {
    ...module,
    rules: [
      { test: /\.json$/, loader: 'json-loader' },
      {
        test: /\.js?$/,
        exclude: '/node_modules/',
        use: [
          {
            loader: 'babel-loader',
          },
        ],
      },
      {
        test: /\.tsx?$/,
        exclude: '/node_modules/',
        use: [
          {
            loader: 'babel-loader',
            options: {
              presets: ['es2015'],
            },
          },
          {
            loader: 'ts-loader',
          },
        ],
      },
      ...module.rules,
    ],
  },
  resolve: {
    ...resolve,
    extensions: [
      `.${platform}.js`,
      '.ts',
      '.tsx',
      `.${platform}.ts`,
      '.native.ts',
      `.${platform}.tsx`,
      '.native.tsx',
      ...resolve.extensions,
    ],
  },
});
```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  beta 10
| react-native     |  0.50.3
| node             |  8.9.1
| npm or yarn      | 1.3.2

**Comment by thymikee** [comment]
Make sure you disable live reloading while using hot reload with Haul.

**Comment by stief510** [comment]
Yeah, it is disabled in the simulator

**Comment by satya164** [comment]
HMR works via `react-hot-loader` which is a Babel plugin. Not sure if it will work with Typescript.

**Comment by stief510** [comment]
According to their documentation it does work with typescript

**Comment by zamotany** [comment]
But you still need to have `react-hot-loader/babel` specified in `plugins` in `babel-loader`'s options or in `.babelrc`.

**Comment by stief510** [comment]
I think I got it working actually by adding `loader: 'react-hot-loader/webpack'` to my webpack file

**Comment by zamotany** [comment]
Haul uses `react-hot-loader` which allows to use either a loader (`react-hot-loader/webpack`) or a babel plugin (`react-hot-loader/babel`), which we add in default webpack config. As for TS, using a loader might be a better option.

Closing since it looks like the issue is resolved and due to inactivity.
