### ISSUE TITLE
Issue with SASS Loader.

### ISSUE THREAD

**Issue by poojajangid25** [callstack/haul#312]
**Current Behaviour**
Failed to compile the app, Showing error - 

> ./app/style.css
> Module parse failed: Unexpected token (1:0)
> You may need an appropriate loader to handle this file type.
> | .container {
> |   position: absolute;
> |   display: inline-block;
> @ ./app/myindex.js 1:1729-1751
> @ ./index.js
> @ multi ./node_modules/haul/src/utils/polyfillEnvironment.js ./index.js

**Expected Behaviour**
I need to load the style.scss file so as to apply the styling in myIndex.js file.

For detail, I started by adding Haul as a dependency to my initial React Native project and configured project to use haul. 
Initially it build the app.
Then created a separate style.scss file for the respective Index.js and configured the webpack.haul.js file.

**Haul Configuration (webpack.haul.js)**

```
const ExtractTextPlugin = require("extract-text-webpack-plugin");

const extractSass = new ExtractTextPlugin({
    filename: "[name].[contenthash].css",
    disable: process.env.NODE_ENV === "development"
});

module.exports = ({ platform }) => ({
  entry: `./index.js`,
  module: {
        rules: [
                  {
                    test: /\.scss$/,
                    use: extractSass.extract({
                        use: [{
                            loader: "css-loader"
                        }, {
                            loader: "sass-loader"
                        }],
                        // use style-loader in development
                        fallback: "style-loader"
                    })
                  }
              ]
    },
    plugins: [
        extractSass
    ],
    resolve: {
        extensions: [ '.js' ]
    }
});

```

 **Environment**
MacOS Sierra
veriosn 10.12.6

npm or yarn : 5.5.1 / 1.3.2
react-native : 0.51.0
react-native-cli : 2.0.1
node : v8.9.2

**Comment by satya164** [comment]
There are 3 issues:

1. React Native is not web. You cannot use CSS/Sass with React Native. You need to use the [`StyleSheet` API](https://facebook.github.io/react-native/docs/stylesheet.html) for styling.
2. You're not merging the default values. You need to merge the default values when modifying the config, see https://github.com/callstack/haul/blob/master/docs/Configuration.md
3. Your webpack configuration doesn't handle files with the `.css` extension.

Hope this clears it up.
