### ISSUE TITLE
Haul not working with Shoutem UI

### ISSUE THREAD

**Issue by sky-franciscogoncalves** [callstack/haul#314]
### Current Behavior

I have been using Haul in a RN application without any problems. However, since I added [Shoutem UI](https://github.com/shoutem/ui) to my app, I'm getting several errors like the ones below:
 
```
(ios) ./node_modules/@shoutem/theme/src/StyleProvider.js
Module parse failed: Unexpected token (9:19)
You may need an appropriate loader to handle this file type.
|  */
| export default class StyleProvider extends React.Component {
|   static propTypes = {
|     children: PropTypes.element.isRequired,
|     style: PropTypes.object,
@ ./node_modules/@shoutem/theme/index.js 3:0-48
@ ./node_modules/@shoutem/ui/components/Lightbox.js
@ ./node_modules/@shoutem/ui/index.js
@ ./lib/AppNavigator.js
@ ./App.js
@ ./index.js
@ multi ./node_modules/haul/src/utils/polyfillEnvironment.js ./index.js

(android) ./node_modules/@shoutem/ui/components/Text.js
Module parse failed: Unexpected token (10:6)
You may need an appropriate loader to handle this file type.
|   render() {
|     return (
|       <RNText {...this.props} />
|     );
|   }
@ ./node_modules/@shoutem/ui/index.js 48:0-54:27
@ ./lib/AppNavigator.js
@ ./App.js
@ ./index.js
@ multi ./node_modules/haul/src/utils/polyfillEnvironment.js ./index.js
```

### Expected Behavior
I expected to be able to use Haul with Shoutem as I'm with every other module I've added to the app. I understand this might be related with a loader that I should be using in Haul. Though, I'm not being able to figure it out. Do you have any recommendation?
### Haul Configuration (webpack.haul.js)
I am using the default configuration.

```
module.exports = ({ platform }) => ({
  entry: `./index.js`,
});
```

By searching around in other issues, namely #220, I have also tried the following configuration.

```
module.exports = ({ platform }, {module}) => ({
  entry: `./index.js`,
  module: {
    ...module,
    rules: [
      {
        test: /\.js?$/,
        exclude: '/node_modules/',
        use: [
          {
            loader: 'babel-loader'
          }
        ]
      },
      ...module.rules
    ]
  }
});

```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-beta.11
| react-native     |  0.50.3
| node             | v8.9.1
| yarn      | 1.3.2

**Comment by Krizzu** [comment]
Hey @sky-franciscogoncalves 

Looks like shoutem is not transpiled. In your configuration, can you try to spread `module.rules` first? Your rule might be overwritten

**Comment by sky-franciscogoncalves** [comment]
Hey @Krizzu,

Thanks for replying so quickly.

I have updated my configuration as you said. 

```js
module.exports = ({ platform }, { module }) => ({
  entry: `./index.js`,
  module: {
    ...module,
    rules: [
      ...module.rules,
      {
        test: /\.js?$/,
        exclude: "/node_modules/",
        use: [
          {
            loader: "babel-loader"
          }
        ]
      }
    ]
  }
});

```

Also, my .babelrc file looks this:
```js
{
  presets: ["es2015", "react", "react-native", "stage-0"],
  plugins: [
    "transform-regenerator",
    "transform-runtime",
    "transform-class-properties"
  ]
}

```
When I run the app I get the following error:
```
Unhandle JS Exception: Object is not a function(near  '...$export...')
```

**Comment by Krizzu** [comment]
cc @zamotany

**Comment by zamotany** [comment]
The `exclude` property in the following rule configuration: 
```js
      {
        test: /\.js?$/,
        exclude: "/node_modules/",
        use: [
          {
            loader: "babel-loader"
          }
        ]
      }
```
is excluding everything in `node_modules` like `node_modules/@shoutem/ui`.

So you either need to convert it to regex with negative lookahead for `@shoutem` like so:
```js
      {
        test: /\.js?$/,
        exclude: /node_modules(?!\/@shoutem)/,
        use: [
          {
            loader: "babel-loader"
          }
        ]
      }
```
or use `include` property to apply this rule only to Shoutem:
```js
      {
        test: /\.js?$/,
        include: [
          /node_modules\/@shoutem/,
        ],
        use: [
          {
            loader: "babel-loader"
          }
        ]
      }
```

I recommend to use 2nd approach with `inlude` as the first one will apply `babel-loader` twice to most of the source files, thus the 2nd approach will be more performant.

**Comment by sky-franciscogoncalves** [comment]
Thanks @Krizzum, @zamotany. I was able to set it up on iOS, I had to do one more change though.

```
module.exports = ({ platform }, { module }) => ({
  entry: `./index.js`,
  module: {
    ...module,
    rules: [
      ...module.rules,
      {
        test: /\.js?$/,
        include: [
          /node_modules\/@shoutem/,
          /node_modules\/react-native-vector-icons/
        ],
        use: [
          {
            loader: "babel-loader"
          }
        ]
      }
    ]
  }
});
```

On the other hand, on Android I'm getting:

```
Unexpected use of reserved word 'import'
```

**Comment by Krizzu** [comment]
@sky-franciscogoncalves Can you post red screen please? To me, seems like something else is not transpiled.

**Comment by sky-franciscogoncalves** [comment]
@Krizzu Never mind, I have reset the cache and everything's working now.

Really appreciated your help!

**Comment by zaguiini** [comment]
> @Krizzu Never mind, I have reset the cache and everything's working now.
> 
> Really appreciated your help!

What do you mean with "reset the cache"? I can't do this...
