### ISSUE TITLE
HMR does not work on device

### ISSUE THREAD

**Issue by tazsingh** [callstack/haul#317]
### Current Behavior
When using HMR, the host is hardcoded to `localhost` which does not load across network as the server is running on whatever IP from my machine.

Therefore the device does not pick up the server and I get an error.
Even with HMR disabled from the device, the JS bundle still fails to load due to the HMR configuration being provided as build time by Webpack.

### Expected Behavior
I can get HMR to work by hardcoding my server's IP at:
- https://github.com/callstack/haul/blob/master/src/utils/makeReactNativeConfig.js#L66
- https://github.com/callstack/haul/blob/master/src/utils/makeReactNativeConfig.js#L122

However this is of course not an ideal solution. Instead, what do you think of passing in a `host` option to the CLI? It could default to the current local IP of the machine, but that would be an enhancement.

### Haul Configuration (webpack.haul.js)

```js
module.exports = () => ({
  entry: `./src/index.js`,
})
```

### Your Environment

I'm currently testing on an iPhone X with iOS 11. But this should be an issue for HMR on all devices.

| software         | version
| ---------------- | -------
| Haul             | v1.0.0-beta.11 from my fork for #315 plus the hardcoded values described above
| react-native     |  0.50.3
| node             | 8.5.0
| npm or yarn      | 1.3.2

### Other notes
I've tried to fix this with the proposed solution above (i.e. pass in a `host` option to CLI), however I don't seem to have all the correct details of this approach working. The end result of `makeReactNativeConfig.js` isn't building with the correct `host` (as well as passing the `host` elsewhere within `haul`). If I end up getting it all working, I'll send up a PR!

**Comment by zamotany** [comment]
This issue is tied specifically to iOS only, Android devices still use `localhost` adress for HMR client/server communication.
