### ISSUE TITLE
Unhandled JS Exception: Can't find variable self

### ISSUE THREAD

**Issue by SanyasiraoM** [callstack/haul#318]
When I run "npm run haul start -- --platform ios", It's loading 100% and says you are ready to run. But after installing app through xcode, It's showing error as in image. I don't know what am I missing, But it's working fine in other systems with same versions I mentioned below

![img_0043](https://user-images.githubusercontent.com/8909624/34599011-50f15e5e-f216-11e7-834a-dd66638e69e5.PNG)

### Haul Configuration (webpack.haul.js)
```
module.exports = ({ platform }, { module, resolve }) => ({
  entry: `./index.${platform}.js`,
  module: {
    ...module,
    rules: [
      {
        test: /\.json$/,
        loader: 'json-loader'
      },
      ...module.rules
    ]
  },
  resolve: {
    ...resolve,
    extensions: ['.json', ...resolve.extensions]
  }
})

```

### Your Environment
MAC

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-beta.7
| react-native     |  0.48.4
| node             | 8.7.0
| npm or yarn      | npm

**Comment by Krizzu** [comment]
Hey @SanyasiraoM 

This IP address (192.168.2.25.xio.io) looks very odd to me. 
Can you show me the content of your `/etc/hosts` files? Might be that your `localhost` is mapped to something different than 127.0.0.1

**Comment by SanyasiraoM** [comment]
@Krizzu Thanks for reply,

Below is my /etc/hosts file

##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost

**Comment by SanyasiraoM** [comment]
As suggested in https://github.com/facebook/react-native/issues/12786, DISABLE_XIP also did not work for me

**Comment by Krizzu** [comment]
Once you disable XIP, do you still get an address ip `192.168.2.25.xip.io` in error message ?

**Comment by zamotany** [comment]
Does is happen in iOS simulator or only on real device?

**Comment by SanyasiraoM** [comment]
@zamotany Real device

**Comment by zamotany** [comment]
It's hard to tell what might be causing this problem. I don't believe the issue is connected to installing app with xcode - I've done it multiple times without a red screen.
@SanyasiraoM Can you create a fresh project to see if the error is still being thrown?

**Comment by SanyasiraoM** [comment]
@zamotany Will try it

**Comment by SanyasiraoM** [comment]
@zamotany No.

**Comment by jrylan** [comment]
@SanyasiraoM I'm still completely stuck. I'll post the solution here if I figure it out.

**Comment by zamotany** [comment]
@SanyasiraoM @jrylan We have made few changes in latest versions of Haul, please update you projects and check if the issue is still happening.

**Comment by jrylan** [comment]
@SanyasiraoM @zamotany My solution was to use the following in my `webpack.haul.js` file:

```js
module.exports = ({ platform }, defaultWebpackConfig) => {
  defaultWebpackConfig.output.globalObject = 'this'

  return {
    entry: `./index.js`
  }
}
```

This prevents Webpack from trying to use `self` and instead forces it to always use `this` for referencing globals, which is safer for web workers (Webpack is smart enough to define additional variables such as `_this` to handle scoping issues).

**Comment by zamotany** [comment]
@jrylan Hmm, interesting. Wondering if HMR still works with this change.

**Comment by zamotany** [comment]
This should not be an issue in `@haul-bundler/cli`.
