### ISSUE TITLE
Typescript + Haul + Storybook

### ISSUE THREAD

**Issue by Burnsy** [callstack/haul#322]
Hey Devs, 
 
I have been working on adding typescript to my workflow, before I was running Haul + storybook. As seen on the storybook repo ([link](https://github.com/storybooks/storybook/tree/master/app/react-native)) it suggests how to use haul with it. That worked as expected using a second configuration file. But adding in typescript Recipe makes it not quite work In src. By the looks of it all that the config needs to do is read from the javascript and if it detects typescript changed then to run the Recipe. 

Is that possible? 

Thanks

**Comment by Krizzu** [comment]
Hey @Burnsy 

Can you show me your config file? (according to storybook, it should be named like `webpack.haul.storybook.js`)

**Comment by Burnsy** [comment]
We scrape using storybook for now as it was hard to implement as it is not wrote with typescript in mind.
