### ISSUE TITLE
Prototype website with docosaurus

### ISSUE THREAD

**Issue by zamotany** [callstack/haul#325]

**Comment by FLGMwt** [comment]
Hi! I started poking at this on a flight if that's alright :)

Anything we're looking for aside from making the current markdown docs available? And any preference for color scheme?

I don't have a bunch of UX chops, but I can get the skeleton and wireup PR'd in the next week.

**Comment by thymikee** [comment]
Awesome! Docs are enough for starters :) Pick whatever color you like that matches our logo and we can iterate.
cc @grabbou

**Comment by zamotany** [comment]
@FLGMwt One thing to keep in mind: docosaurus doesn't support nested directories in `docs` so you need to update markdown files itself to make them flat.

**Comment by thymikee** [comment]
Note: we have a reserved domain `haulcli.org`, would be nice to hook it up!

**Comment by thymikee** [comment]
Closed via #374
