### ISSUE TITLE
Xcode error

### ISSUE THREAD

**Issue by xuyunan** [callstack/haul#329]
I got an error when run app in xcode:

sed: /Users/tommy/React: in-place editing only works for regular files
../node_modules/haul/src/utils/haul-integrate.sh: line 19: ${SRC}/packager.sh: ambiguous redirect
Command /bin/sh failed with exit code 1

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  1.3.2
| react-native     |  0.52.0
| node             |  8.9.3
| npm or yarn      | yarn

**Comment by thymikee** [comment]
@xuyunan does this help? https://github.com/callstack/haul/issues/234#issuecomment-342728131

**Comment by xuyunan** [comment]
@thymikee yes, error is gone.
