### ISSUE TITLE
adb reverse command assumes adb is in /opt

### ISSUE THREAD

**Issue by hedgepigdaniel** [callstack/haul#331]
### Current Behavior

When running haul, I see the message ` WARN  Error running adb reverse tcp:8081 tcp:8081: /bin/sh: /opt/android-sdk/platform-tools/adb: No such file or directory`

### Expected Behavior

It should correctly run adb, which is available in my `$PATH` at `/usr/bin/adb`

### Your Environment

I'm running Arch Linux, and the problem occurs with this package installed: https://www.archlinux.org/packages/community/x86_64/android-tools/

The problem does not occur if I also install this package (but this one doesn't put its binaries somewhere in the default $PATH): https://aur.archlinux.org/packages/android-sdk-platform-tools/

For me, I don't need this to work because I'm using `react-native run-android` to run my app, which independently runs `adb reverse`. I assume its necessary in some circumstance though.

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-beta.12
| react-native     |  0.52.0
| node             |  9.4.0
|  yarn      | 1.3.2

**Comment by jukben** [comment]
Hi @hedgepigdaniel I agree that we should run `adb` from path at first. I've created the PR for it, so let's wait what others think.
