### ISSUE TITLE
React Native 0.52 Android Delta Bundles

### ISSUE THREAD

**Issue by Traviskn** [callstack/haul#334]
In the latest version of react native, android by default tries to load a new 'delta' bundle.
(See: https://github.com/facebook/react-native/blob/79e24ede40b2508aaa77b8ff3876d3dbf4cfe6d8/ReactAndroid/src/main/res/devsupport/xml/preferences.xml)
This results in an error when using Haul because the app requests an `index.delta` file that is not being served.

The fix is simple though, open the dev menu, select the "Dev Settings" option, then uncheck the "Use JS Deltas" box.  Close then re-open your app and it should request the normal javascript bundles as before.

**Comment by dave-irvine** [comment]
This is covered by a PR already :) https://github.com/callstack/haul/pull/327

**Comment by thymikee** [comment]
Closed #334 via #327. Expect it in the next beta release.

**Comment by tkow** [comment]
I'm sorry to reopen issue. I want to ask you for detox integration.
I cannot disable delta bundles running 
```
detox test --configuration android.emu.debug 
``` 
command and an error emitted  show.

![2018-03-29 10 52 11](https://user-images.githubusercontent.com/7004725/38065717-b256629c-333f-11e8-94cf-6bb3cfb3e317.png)

Even if we unchecked using DeltaBundles' check box and restart running test, it doesn't work and the same error shows.

Can it be disable  with configuration file or from command line like additional options? or I should wait for next release ?

**Comment by thymikee** [comment]
@Strate have you tried `beta.14` or `rc.0` (with Webpack 4 so breaking)?

**Comment by Strate** [comment]
@thymikee I am on 1.0.0-beta.14.

Fixed with modifying `onCreate` method in `MainApplication.java`:

```java
 @Override
    public void onCreate() {
        super.onCreate();
        DevInternalSettings settings = (DevInternalSettings) getReactGateway().getReactInstanceManager().getDevSupportManager().getDevSettings();
        settings.setBundleDeltasEnabled(false);
    }
```

**Comment by simonbuchan** [comment]
I'm not sure what `getReactGateway()` is, but for the `MainApplication.java` we have, `getReactNativeHost()` instead works fine.

**Comment by Strate** [comment]
Updated my reciepe, to support prod mode
