### ISSUE TITLE
Can Haul load modules dynamically like a React Native packager?

### ISSUE THREAD

**Issue by jasesuperhero** [callstack/haul#340]
React Native Packager can load modules dynamically. For example, we can load jsbundle to the app and use this code to load it to out app:
```javascript
[RCTJavaScriptLoader loadBundleAtURL:PATH
                              onProgress:nil
                              onComplete:nil];
```
But with Haul (Webpack) we should describe all out paths in config file in entry section. Could Haul load bundles in runtime? Or Webpack? 
Sorry, if this question is some strange :(

**Comment by hedgepigdaniel** [comment]
Webpack [can definitely do that](https://webpack.js.org/guides/code-splitting/), not sure how it fits in to haul and react-native

**Comment by thymikee** [comment]
Code splitting in RN is done differently than on web. I think this is a matter of Haul supporting RAM bundles. Definitely something we should explore.
