### ISSUE TITLE
NSURLErrorNetworkConnectionLost error with dev build

### ISSUE THREAD

**Issue by savelichalex** [callstack/haul#341]
### Current Behavior
Frequently get error while debugging app on device. Error is: `Failed to load bundle(http://(my_ip).xip.io:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(Could not connect to development server.)`
My device in the same wi-fi network.
Packager is started (and I see logs in terminal with GET requests for bundle)

### Expected Behavior

Correct bundle loading

### Haul Configuration (webpack.haul.js)

```js
const webpack = require('webpack');
module.exports = ({ platform }, { module, resolve }) => ({
  entry: `./src/index.tsx`,
  devtool: 'eval-source-map',
  module: {
    ...module,
    rules: [
      {
        exclude: '/node_modules/',
	test: /\.tsx?$/,
	use: [
	  { loader: 'babel-loader' },
	  { loader: 'ts-loader' },
	]
      },
      ...module.rules
    ]
  },
  resolve: {
    ...resolve,
    extensions: [
      '.ts',
      '.tsx',
      ...resolve.extensions,
    ]
  },
  plugins: [
    new webpack.DefinePlugin({
      '__DEV__': true
    }),
    ...resolve.plugins
  ]
});
```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  @1.0.0-beta.11
| react-native     |  0.51.0
| node             | 8.4.0
| npm      | 5.4.1

# Details
I'm debugging whole process for bundle loading in bridge and I found that this is `NSURLErrorDomain` with code `1005`, what mean `NSURLErrorNetworkConnectionLost`.
Corresponding page on Apple documentation https://developer.apple.com/library/content/qa/qa1941/_index.html . Also I found this answer on SO, that can help https://stackoverflow.com/a/25996971/2822639 .

I can help with this problem if you give me some advice, especially about `Keep-alive` settings.

**Comment by savelichalex** [comment]
Oh my, looks like I found workaround with this issue. The problem is big bundle size (with sourcemaps etc), in this case node fail with `keepAliveTimeout`, so I set `httpServer.keepAliveTimeout = 30000` (in `src/server/index.js`) and it's working now.

**Comment by thymikee** [comment]
Thanks for coming back with the answer @savelichalex!

**Comment by savelichalex** [comment]
@SuhairZain I'm using 1.0-rc in new project and it seems that problem is disappeared

**Comment by savelichalex** [comment]
Seems like I need to use this patch with `keepAliveTimeout` again on `1.0.0-rc.14` version
