### ISSUE TITLE
Allow running haul as a non interactive child process

### ISSUE THREAD

**Issue by kcjonson** [callstack/haul#343]
This issue/enhancement is best explained with a bit of background, so bear with me.

At Redfin we work in a “monorepo” and use Lerna and Yarn to manage a large number of private npm packages. These packages range from things like our UI Toolkit and general utilities, to feature code. Each of these packages has its own build and corresponding watch commands. When a developer begins work, we want to enable them to start their developer tools and watch mode for everything in the dependency tree they’re working on. As a basic example, if they’re working on the main website, the build tools need to build and watch their feature code, the UI code, the javascript utilizes, and about 15 other packages. Changing any of the source in these packages should trigger a build for that package then trigger a build for webpack.

Here is a very simplistic view of how this looks, some things have been censored/tweaked so your head doesn't explode.

![unknown](https://user-images.githubusercontent.com/1512633/35304241-acb5e700-0049-11e8-961f-ee2646fbdff3.png)

When a developer starts their tools, we use a global CLI to handle everything

`fin rn -wi`

`rn` - we’re running just the react-native side of things
`-w` - we want to be in watch mode (this is haul)
`-i` - I care about iOS, it will make sure the native build is in a good state, and launch the iOS simulator

Now, at this point, the developer can modify either `homepage.jsx` which will cause haul to rebuild, or `Button.jsx` which will run the ui package build for Button, then trigger haul which will see a change to `Button.js` in the ui package `dist` directory. This is essentially recursive watch along with its pros/cons.  This allows developers to work on any parts of the codebase without opening a bunch of terminal windows or beaming a tmux guru.

_Cool, thats a long intro, thanks for listening. If you think what we’re doing is awful, feel free to email me at kevin@redfin.com, I’m actually totally open to hostile rants about how we’re totally sh***ing the bed on that setup._

Now, lets get into the dirty bits. There is a script. The best script, the greatest script that was ever scripted, that manages these shenanigans. It uses the wonderful [yargs](https://www.npmjs.com/package/yargs) library to parse what the dev is trying to do, and runs the watch code we have. In the watch code is something like this

![unknown-1](https://user-images.githubusercontent.com/1512633/35304252-b7f19c18-0049-11e8-836e-ec3929c7f797.png)

and it also spawns watchers for all the dependencies in the tree with a similar method.

![unknown-2](https://user-images.githubusercontent.com/1512633/35304260-bd942456-0049-11e8-9932-3a42fcba3d8d.png)

These two chunks of code span a handful of sub processes each that each watch a thing in the tree and the app code itself. However, with the stdio inherited from all these things, the console output isn’t particularly friendly, and developers were struggling to find the errors and explain unexpected exits.

_Alright, lots of talking. Lets now talk about specifically about haul._ 

Two things about haul, that you might have thought of:
1) Haul has a bunch of great code that makes the cli wonderfully interactive
2) Haul log output does beautiful and fancy things like progress bars

These were amazing for getting haul up and running, and made it a joy to work with. However, once it came time to integrate into our parent build cli, things got out of hand pretty quick. 

The first thing we need is for haul to operate in non interactive mode, this should be relatively trivial. There are two ways that I could fix up haul to handle this, the first being CLI arg that tells it to stop being so nice and just exit, and/or an _implied_ non interactive mode when haul detects that its being run as a child process. The easiest thing to do is look for `process.send` which is a telltale way to note if there is a parent running the show.  There are a few places where this would have to be done, but here is essentially what `cliEntry.js` would end up like, at the point where friendly haul would ask, it just dumps an error and exits.

![unknown-3](https://user-images.githubusercontent.com/1512633/35304293-cf924a0c-0049-11e8-8b79-fc2be52efc78.png)

The next thing we really want is metrics collection for sending to statsd including things like build timing for incremental builds in seconds, and number of unexpected exits from the process. We also want nice formatting of the output with prefixes on the lines denoting which sub processes they came from.  This means that we can’t just inherit the stdio since we want to do something with it and letting it stream by won’t do. We’ll need to switch our stdio of the haul child process to ipc, then start expecting **structured messages.** 

![unknown-4](https://user-images.githubusercontent.com/1512633/35304305-d90376ce-0049-11e8-976a-8e7756b197d1.png)

And Haul itself must get switched to talk via ipc. Following the same pattern of above, we can look for `process.send` and this time actually use it. This example is from `messages/bundleBuilt.js` There is all sorts of good stuff that comes out of this, the most important of which is that the parent process is now receiving a structured message, complete with raw data. No log/string parsing needed!

![unknown-5](https://user-images.githubusercontent.com/1512633/35304308-dfbcd01e-0049-11e8-82c5-ffd896cd9d3e.png)

I have to interject here that having all (most) the log/console output well refactored into the `messages/` directory makes this a ton easier than I thought it would be. Well done on that pattern, whoever keep all that together gets a beer on me next time you’re in Seattle.

**If this seems like a reasonable path to walk down, I've got a PR mostly together that makes these changes, I wanted to check in before I spent the time to polish it up.**

Alternately, a direct Node API could be created, as mentioned in this issue (https://github.com/callstack/haul/issues/326)
 which seems like more work than this, which is almost done. Although a direct Node API and the subprocess improvements largely might answer the same question, they could also exist in harmony.

**Comment by Krizzu** [comment]
Hey @kcjonson, thanks for your work in putting this together. 
We've been through few internal talks about where Haul is heading and few major conclusions came out of it.
Separating Haul from it's GUI is on our list. We work on dividing Haul into two parts, one being Haul as a tool and other as nice interactive CLI. Also, we'll introduce an event system, where all events across Haul's lifecycle will be available to subscribe to. #326 and #339  are steps toward this goal.

If you have any more questions, don't hesitate to post them here.

Regards

**Comment by thymikee** [comment]
Closing in favor of https://github.com/callstack/haul/issues/326
