### ISSUE TITLE
do we really need "babel-loader" for react native project under Typescript? 

### ISSUE THREAD

**Issue by wangbourne** [callstack/haul#345]
Currently, i have to use both `babel-loader` and `ts-loader` in `webpack.haul.js`, otherwise, if without `babel-loader`, following error happens when running storybook.  My question is: why do i have to use `babel-loader` and what's the reason for that? 

```
./storybook/StorybookUI.tsx
Module parse failed: Unexpected token (21:15)
You may need an appropriate loader to handle this file type.
| class StorybookUIHMRRoot extends React.Component {
|     render() {
|         return <StorybookUIRoot />;
|     }
| }
@ ./storybook/index.ios.ts 3:20-44
@ multi ./node_modules/haul/src/utils/polyfillEnvironment.js ./storybook/index.ios.ts


```

**Comment by Krizzu** [comment]
This looks like a problem of transpiling JSX. Babel-loader uses `react-native` preset, that has JSX transpiling included.

**Comment by thymikee** [comment]
@wangbourne yes we need `babel-loader` to work by default with React Native projects. If you use TypeScript, feel free to override the loader with yours, as stated in [our docs on TypeScript](https://github.com/callstack/haul/blob/f8c7a1034b49ddc4af0d2395b40a2a73d269f6ce/docs/Recipes.md#typescript).
