### ISSUE TITLE
scriptURL is null when building for Release with Xcode

### ISSUE THREAD

**Issue by mattpetrie** [callstack/haul#349]
### Current Behavior

When building with the release build configuration in Xcode, I'm getting the following build error:
```
Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: null is not an object (evaluating 't.match(/(^.+)\/index/)[1]')
```
The error is referring to the minified version of [this line](https://github.com/callstack/haul/blob/172c93acf759e43ee93f1825e683a420a9f8784c/src/utils/polyfillEnvironment.js#L45), so it seems that `NativeModules.SourceCode.scriptURL` being imported from react-native is `null`.

I'm getting this when using haul version 1.0.0-beta-12. With 1.0.0-beta-11, it works just fine (it doesn't include the line that is causing the error).

### Expected Behavior

The build should complete without error as it does in beta-11.

### Haul Configuration (webpack.haul.js)

```
const eslintFormatter = require('react-dev-utils/eslintFormatter')
const paths = require('./paths')

module.exports = ({ platform }, defaults) => ({
  entry: `./index.js`,
  module: {
    ...defaults.module,
    rules: [
      ...defaults.module.rules,
      {
        test: /\.(js|jsx)$/,
        enforce: 'pre',
        use: [
          {
            options: {
              formatter: eslintFormatter,
            },
            loader: require.resolve('eslint-loader'),
          },
        ],
        include: paths.appSrc,
      },
      {
        test: /\.graphql$/,
        exclude: /node_modules/,
        loader: 'graphql-tag/loader',
      },
    ],
  },
})
```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-beta-12
| react-native     |  0.52.0
| node             | 8.9.4
| npm or yarn      | yarn

**Comment by Bolik** [comment]
We have the same bug

**Comment by czystyl** [comment]
@Bolik Can you give your configuration?
@mattpetrie Can you create a repository in which it appears?

**Comment by Bolik** [comment]
const path = require('path'),
      webpack = require('webpack')

module.exports = ({ platform }, {module, resolve, plugins}) => ({
    entry: './src/index.tsx',
    devtool: false,
    module: {
        ...module,
        rules: [
            {
                test: /\.ts(x?)$/,
                use: [
                    {loader: 'babel-loader'},
                    {
                        loader: 'ts-loader'
                    }
                ]
            },
            ...module.rules
        ]
    },
    resolve: {
	...resolve,
        symlinks: false,
        extensions: [".ts", ".tsx", ...resolve.extensions],
        alias: {
            core: path.resolve(__dirname, 'node_modules/medarchive-client-core/dist'),
            assets: path.resolve(__dirname, 'node_modules/medarchive-client-core/dist/assets'),
            etc: path.resolve(__dirname, 'etc'),
            components: path.resolve(__dirname, 'src/components'),

            globalize$: path.resolve(__dirname, 'node_modules/globalize/dist/globalize.js'),
            globalize: path.resolve(__dirname, 'node_modules/globalize/dist/globalize'),
            cldr$: path.resolve(__dirname, 'node_modules/cldrjs/dist/cldr.js'),
            cldr: path.resolve(__dirname, 'node_modules/cldrjs/dist/cldr')
        }
    },
    plugins: [
              new webpack.DefinePlugin({
                  'process.env': {
                      'API_URL': JSON.stringify('https://mb.medarhiv.ru'),
                      'API_WSURL': JSON.stringify('https://mb.medarhiv.ru')
                  }
              }), ...plugins
             ]
});

**Comment by Bolik** [comment]
It's produces only in production mode

**Comment by satya164** [comment]
Makes sense that `scriptURL` is not available in production. Changing `global.DEV_SERVER_ORIGIN = scriptURL.match(/(^.+)\/index/)[1];` to `global.DEV_SERVER_ORIGIN = scriptURL ? scriptURL.match(/(^.+)\/index/)[1] : null;` should fix the issue. What do you think @zamotany ?

**Comment by czystyl** [comment]
Not exactly because scriptUrl is always a string but regex not matched then we try to get [1] element form null and BOOM!  I created PR to fix this.
