### ISSUE TITLE
Guide to Expo with Haul. (Question)

### ISSUE THREAD

**Issue by MichelDiz** [callstack/haul#351]
Hi, greetins

I wanna create aliases using Haul with Exp I got some deadlock with:
```bash
? Enter path to the .xcodeproj file
>>  is not a valid .xcodeproj
```
I'm able to do it in React-Native cus RN has .xcodeproj

So, Haul has no Expo suport?

Best Regards.

**Comment by Krizzu** [comment]
Hey Michel,

Expo gives no access to `iOS` or `android` projects, so if you want to use Haul with Expo, you need to `eject` it.

**Comment by MichelDiz** [comment]
Hey, let me question one more thing. Why this kit https://github.com/sysgears/apollo-universal-starter-kit/tree/fbf315c8fb1d616c9fb4303982d76d1b93d5f2a2/packages/mobile

Use Haul with Expo?

I tried to understand how they use it, but seems not as I want (I just wanna the aliases thing).

Thanks a lot xD

**Comment by Krizzu** [comment]
Hey @MichelDiz, sorry for coming back so late.

To answer that question - They don't use Haul to bundle JS, they just use Haul's babel plugin (https://github.com/sysgears/apollo-universal-starter-kit/blob/3fcd6c5e767a9f448c641b041f7be77d998cf99c/.babelrc.native#L4). It's stated in their README.
