### ISSUE TITLE
Android: Configure location of webpack.haul.js file

### ISSUE THREAD

**Issue by Traviskn** [callstack/haul#352]
I have my webpack.haul.js file located in a `config` folder in my root directory.  During development I've customized my npm start script to pass the config option: `haul start --config config/webpack.haul.js`

When I try to build a release APK for android using `./gradlew assembleRelease` however, the cli cannot find the new location of my haul webpack config, as it expects it to be in the root directory.  I cannot tell how to configure my `android/app/build.gradle` to pass the `--config` option along to Haul.

This is my current `android/app/build.gradle` configuration which matches the docs:
```
project.ext.react = [
    entryFile: "index.js",
    cliPath: "node_modules/haul/bin/cli.js"
]
```

I've tried adding the `extraPackagerArgs` configuration option, but it seems to have no effect
```
project.ext.react = [
    entryFile: "index.js",
    cliPath: "node_modules/haul/bin/cli.js",
    extraPackagerArgs: ["--config", "config/webpack.haul.js"]
]
```

How can I configure my android project to pass the `--config config/webpack.haul.js` option to Haul?

**Comment by zamotany** [comment]
This should be fixed & working in `@haul-bundler/cli`.
