### ISSUE TITLE
Merge webpack plugin configuration / DefinePlugin

### ISSUE THREAD

**Issue by ajcrites** [callstack/haul#362]
### Current Behavior
If you add a `DefinePlugin` section to your `webpack.haul.js` / config plugins, it will override the default DefinePlugin stuff set up for you by `makeReactNativeConfig`. For example, you could have a `webpack.haul.js` like:

```
module.exports = ({ platform }) => ({
  entry: `./index.js`,
  plugins: [
    new webpack.DefinePlugin({
      'API_HOST': JSON.stringify(process.env.API_HOST),
    }),
  ]
});
```

If you try to run your app, you'll get mysterious errors such as `undefined variable __DEV__`, but after looking into it the problem is that the plugins are overridden.

### Expected Behavior
I think there are a few options here.

1. haul should be able to intelligently merge plugins
2. haul should provide documentation / a clear path for merging of plugins
3. Just for my specific case, haul should provide the ability to forward environment variables or other fine grained configuration.

### Haul Configuration (webpack.haul.js)
Sufficient to reproduce:

```
module.exports = ({ platform }) => ({
  entry: `./index.js`,
  plugins: [],
});
```

### Your Environment
| software         | version
| ---------------- | -------
| Haul             | v1.0.0-beta.13  
| react-native     |  0.53.0
| node             | 9.5
| npm or yarn      | 1.3.2

**Comment by ajcrites** [comment]
The base config gets passed as an argument to the exported function to generate the app configuration. This allows you to spread the plugins as well:

    module.exports = (_, { plugins }) => ({
      entry: `./index.js`,
      plugins: [
        new webpack.DefinePlugin({
          ...
        }),
        ...plugins,
      ],
    });

**Comment by satya164** [comment]
We say in the configuration docs that you should merge the passed config yourself. https://github.com/callstack/haul/blob/master/docs/Configuration.md

> If you are want to customize the webpack configuration, like loaders etc., define them as usual, and merge the passed configuration in

It's not possible for Haul to intelligently merge config automatically. It'll be flaky and also prevent people from overriding stuff when they actually need to.

**Comment by baygeldin** [comment]
I'm not sure that just closing the issue is the right way. I think that the issue should be addressed somehow, because merging plugins that are already used internally in Haul is extremely unconvinient and it doesn't documented anywhere. This is the only way I could get it working:
```javascript
let definePluginId = defaults.plugins.findIndex(p => p.constructor.name === 'DefinePlugin');
defaults.plugins[definePluginId].definitions['process.env']['MY_ENV'] = JSON.stringify(process.env.MY_ENV);
```
I do agree that merging should be done manually, but not this way (it's an unreliable and unconvinient ad hoc solution). Ideally, webpack plugins themselves should be able to merge configurations when defined multiple times, but in this case I think that providing some API to swap plugins and fetch their default configuration would already be a huge improvement.

**Comment by jukben** [comment]
This would be lots of easier with this PR https://github.com/callstack/haul/pull/372, still in the progress but I hope it will be soon in the master! Stay tuned. 🙏

**Comment by baygeldin** [comment]
@jukben sounds great. I looked through the PR, but couldn't understand how it could solve the problem for DefinePlugin though. Could you elaborate a bit? Thanks!

**Comment by jukben** [comment]
You are right. In this case, the effect would be the same. It will be cleaner, but you have to still find the plugin and rewrite it manually.

**Comment by satya164** [comment]
@baygeldin with the new config format you can use something like [webpack-merge](https://github.com/survivejs/webpack-merge) to do the merging. I think it's better that we don't try to solve this problem because there are other tools which try to solve it already.

**Comment by baygeldin** [comment]
That's a good point. Although looking at `webpack-merge` sources I'm not sure if it can merge plugins configuration, but it can swap plugins though. Anyway, `babel-plugin-transform-inline-environment-variables` works perfectly for my usecase, so it's okay. Thanks for your help. Keep it up, Haul is a great tool :)
