### ISSUE TITLE
Investigate custom React Native environment target for Webpack

### ISSUE THREAD

**Issue by zamotany** [callstack/haul#369]
Webpack allows to pass custom `target`, currently we use `webworker` one, however while working on migration to Webpack 4 we have faced few non-trivial issues, it might be a better idea to create our custom templates for Webpack _bootstrap code_, which would be still based on `webworker` but with few changes.

**Comment by thymikee** [comment]
Let's do this!

**Comment by Jekiwijaya** [comment]
This would be useful for creating split bundles

**Comment by zamotany** [comment]
Something similar is already done on `next` branch.
