### ISSUE TITLE
SVG assets do not seem to load

### ISSUE THREAD

**Issue by mtimofiiv** [callstack/haul#371]
### Current Behavior

I have a pretty early stage RN app (testing it in the iOS simulator), so there's not much custom stuff in it, but I am using Haul. I have some SVG images I wanted to use in it, and am attempting to display them using:

```
<Image source={require('PATH_TO_MY_IMAGE')} width={30} height={30} />
```

What's happening is that the image is not showing up in place. The packager instance is showing the following:

```
GET /index.ios.bundle 200 21393585 - 26.269 ms
GET /assets/ios/assets/home.svg 304 undefined - 0.480 ms
```

The bundle is served and the image is also (with a `304` response code). For testing's sake I attempted to enter a wrong URI into the `require` statement and it did indeed throw the red screen of death telling me the asset cannot be located.

So as far as I can tell, Haul is finding it, resolving it, but it is not showing.

### Expected Behavior

Obvs, I am expecting the image to show up in place.

### Haul Configuration (webpack.haul.js)

```js
module.exports = ({ platform }, { module }) => ({
  entry: `./index.js`,
  module: {
    ...module,
    rules: [
      {
        test: /\.js?$/,
        exclude: '/node_modules/',
        use: [
          {
            loader: 'babel-loader'
          }
        ]
      },
      ...module.rules
    ]
  }
});
```

### Your Environment

Nothing special, I am running RN, Haul and the iOS sim that comes with XCode on a MacOS 10.13.3.

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-beta.13
| react-native     |  0.52.1
| node             | 9.4.0
| npm or yarn      | yarn 1.3.2

**Comment by satya164** [comment]
React Native doesn't support SVG images. That's probably why it doesn't show up.

**Comment by mtimofiiv** [comment]
Ok, thanks, I guess I was not aware.
