### ISSUE TITLE
index.android.bundle problem

### ISSUE THREAD

**Issue by PeterKottas** [callstack/haul#373]
### Current Behavior
App breaks with red screen of death. The error reads:
"Can't find variable: document (http://10.0.2.2:8081)/index.bundle?platform=android&dev=true&minify=false:3"

Haul server says
GET /index.android.bundle 500 undefined - 3.402 ms
POST /symbolicate 404 151 - 1.223 ms

I verified that I can in fact open http://10.0.2.2:8081)/index.bundle, however the app seems to be asking for index.android.bundle instead for some reason. I've tried to specify the filename in webpack config, both as index.bundle and index.android.bundle.

First didn't work, second changed the 500 undefined error in haul server to 200 ok but app still asks for index.bundle and the red screen stayed the same. I also tried without the output section and the result was same as specifying index.android.bundle specifically. 

### Expected Behavior
It should work without errors.

### Haul Configuration (webpack.haul.js)
const path = require('path');

module.exports = ({ platform }, defaults) => ({
    entry: {
        'index': './ClientApp/index.tsx'
    },
    resolve: {
        ...defaults.resolve,
        extensions: [
            '.ts',
            '.tsx',
            `.${platform}.ts`,
            '.native.ts',
            `.${platform}.tsx`,
            '.native.tsx',
            ...defaults.resolve.extensions
        ],
        alias: {
            ...defaults.resolve.alias,
            'react-native': 'react-native-web',
        }
    },
    module: {
        ...defaults.module,
        rules: [
            {
                test: /\.(ts|tsx)$/,
                include: [
                    path.resolve(__dirname, 'ClientApp'),
                ],
                use: 'awesome-typescript-loader?silent=true'
            },
            ...defaults.module.rules
        ]
    },
    output: {
        ...defaults.output,
        filename: 'index.bundle',
        //filename: 'index.android.bundle',
    },
});
### Your Environment
Windows 10

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-beta.13
| react-native     |  0.53.3
| node             | v9.5.0
| yarn      | v1.3.2

Any help much appreciated, thanks!

**Comment by PeterKottas** [comment]
Btw, I've checked some issues that appears to be talking about similar topic but found nothing that would have helped with my problem. All of those were either marked as fixed, or provided workarounds that didn't work for me.

**Comment by zamotany** [comment]
Logs within Haul will be always pointing to `GET /index.android.bundle` even though `index.bundle` will be served. This for backwards comaptibility reasons.

Please confirm you can get a actual bundle at `http://localhost:8081/index.bundle?platform=android` and make sure it contains JS code not any html tags, which might happen if server cannot find requested file.

**Comment by PeterKottas** [comment]
Ok good to know that about logs, I though that was the problem.
Yep I can get the file http://localhost:8081/index.bundle?platform=android in the browser and on the emulator. I also tried removing the output.filename (only put it there to try to fix the problem) but nothing changed.

**Comment by PeterKottas** [comment]
In fact, it actually loads http://10.0.2.2:8081/index.bundle ... just for completeness sake. That's obviously the way to connect to host machine which is just an implementation detail on android I guess. It works via localhost as well though.

**Comment by zamotany** [comment]
Yeah, `10.0.2.2` is mapped to `localhost` within android emulator/device.
The error _Can't find variable: document_ means that there is some code, which tries to use `document` variable, which is not available in React Native.

So, you should look at the stack trace, probably it will point to `index.bundle`, so then find that line in bundle code and scroll up to see the module path. Then you'll know what is using `document` variable.

**Comment by PeterKottas** [comment]
Thanks mate, it was definitely a confusion cause by that log line that mentioned index.android.bundle and the face the I aliased 'react-native': 'react-native-web'. Now it's all good. Thanks again for this cool tool! I'll be in touch if I find something of real value.
