### ISSUE TITLE
`haul init` clobbers existing project.ext.react gradle config

### ISSUE THREAD

**Issue by FLGMwt** [callstack/haul#376]
### Current Behavior
`haul init` adds the following block to my project's `android/app/build.gradle` above the `react.gradle` import, which overwrites my existing `project.ext.react` assignment.

```
project.ext.react = [
    cliPath: "node_modules/haul/bin/cli.js"
]
```

### Expected Behavior
`haul init` should merge the new `cliPath` property into `project.ext.react` config if it exists, *or* fall back to the current behavior and create a new `project.ext.react` block.

### Haul Configuration (webpack.haul.js)
```
module.exports = () => ({
  entry: `./index.js`,
});
```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-beta.13
| react-native     |  0.53.0
| node             | v9.3.0
| npm or yarn      | v1.3.2

Workaround is just to manually merge the two `project.ext.react` blocks, but it'd be nice if `haul init` did this for you.

It looks like it just needs a bit more logic where it adds this block [here](https://github.com/callstack/haul/blob/33775258ab1b801d1e0a4762a72fc3b78844c0bf/src/commands/init.js#L266)

I'm happy to PR a fix in the coming week : )

**Comment by zamotany** [comment]
Maybe we should change the way we update `android/app/build.gradle` to use some diffing library like `jsdiff` and just apply a patch by only overwriting `cliPath`? @satya164 @Krizzu @jukben @thymikee

**Comment by thymikee** [comment]
If that helps the case, but we can also search for existing `project.ext.react` and bailout with a proper warning to the user

**Comment by zamotany** [comment]
Well I was thinking about having a patch fixture containing:
```
project.ext.react = [
    cliPath: "node_modules/haul/bin/cli.js"
]
```
then we would diff it against the actual file, if user already has `project.ext.react` the diff would be smaller and only `cliPath` will be overwritten. Or sth along those lines (detailed explanation in progress).

**Comment by satya164** [comment]
> use some diffing library like jsdiff and just apply a patch by only overwriting cliPath

Whatever works :D

> detailed explanation in progress

(patiently waiting)

**Comment by FLGMwt** [comment]
I think we can get away with not doing anything clever string-wise (since we'd have to deal with comments. Since we're doing the replacing right about the `react.gradle` import and I *think* we can be reasonably sure this is the furthest down in the config that the user would assign their own `ext.react` values, how about just swapping out the snippet with a graceful initialization of `ext.react` and then a more surgical `cliPath` assignment? We'd end up with giving the user the following:

```
if (!project.hasProperty('react')) {
    project.ext.react = [:]
}
project.ext.react['cliPath'] = "node_modules/haul/bin/cli.js"

apply from: "../../node_modules/react-native/react.gradle"
```
