### ISSUE TITLE
JS Exception while creating Release build with Xcode

### ISSUE THREAD

**Issue by tutts** [callstack/haul#378]
### Current Behavior

Hi 👋 

Haul works perfectly in xcode while the Build Configuration in the Schema is set to `Debug`, however running as `Release` seems to cause the app to crash after building.

On build the packager loads and bundles successfully:

```
DONE  Built successfully in 51.93s!

You can now run the app on your ios device
```

Installs onto the simulator (or device) and then throws an exception:

```
STDERR
E0301 18:07:48.382313 138477568 JSCHelpers.cpp:137] Got JS Exception: null is not an object (evaluating 't.match(/(^.+)\/index/)[1]') 
```

Had a look as to what might be causing it, and I _think_ its this line here `haul/src/utils/pollyfillEnvironment.js`

```javascript
const scriptURL = require('react-native').NativeModules.SourceCode.scriptURL;
global.DEV_SERVER_ORIGIN = scriptURL.match(/(^.+)\/index/)[1];
```

I thought it might have to do with the entrypoint for the bundle because we use codepush, but changing that still caused the crash, but included below fwiw.

```objective-c
  NSURL *jsCodeLocation;
  
  // Loading JavaScript code
  #if DEBUG
    // For Debug build load from development server. Start the server from the repository root:
    //
    // $ npm start
    #if TARGET_IPHONE_SIMULATOR
      // Run from locally running dev server
      jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.bundle?platform=ios&dev=true"];
    #else
      // Run on device with code coming from dev server on PC (change the IP to your PCs IP)
      jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
    #endif
  #else
    // For production load from pre-bundled file on disk. To re-generate the static bundle, run
    jsCodeLocation = [CodePush bundleURL];
  #endif
```

Not sure where to go from there in terms of debugging, but if anyone has any guidance please do let me know!

Thanks!
Sam

### Expected Behavior

Bundles and loads with Build Configuration set to `Release`
 
### Haul Configuration (webpack.haul.js)

```jaavascript
module.exports = ({ platform }, { module }) => ({
  entry: `./index.js`,
  module: {
    ...module,
    rules: [
      {
        test: /\.js?$/,
        exclude: '/node_modules/',
        use: [
          {
            loader: 'babel-loader',
          },
        ],
      },
      ...module.rules,
    ],
  },
})

```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-beta.13
| react-native     |  0.51
| node             |  8.9.1
| npm or yarn      | 5.5. / 1.3.2 (use yarn though)

**Comment by Krizzu** [comment]
Hey @tutts 
We already fixed that https://github.com/callstack/haul/pull/363

Going to release soon, hopefully, cc @grabbou @satya164

**Comment by tutts** [comment]
oh snap! amazing, thanks so much. I searched through all the open/closed issues but not the MRs. Doh! Thanks for the amazing work guys.
