### ISSUE TITLE
[ Android ] Unable to hot reload whilst debugging JS remotely

### ISSUE THREAD

**Issue by ndillon1** [callstack/haul#379]
### Current Behaviour
Run the following command 
`yarn run haul start --platform android`
The app bundles successfully however when trying to hot reload components , I am receiving the following errors 
`http://10.0.2.2:8081/0.508ca35a4baeb9f81480.hot-update.js net::ERR_CONNECTION_TIMED_OUT`

```
[HMR] Update check failed: Error: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://10.0.2.2:8081/0.508ca35a4baeb9f81480.hot-update.js' failed to load.
    at hotDownloadUpdateChunk (eval at evalJS (http://localhost:8081/debuggerWorker.js:64:11), <anonymous>:9:12)
    at hotEnsureUpdateChunk (eval at evalJS (http://localhost:8081/debuggerWorker.js:64:11), <anonymous>:270:13)
    at eval (eval at evalJS (http://localhost:8081/debuggerWorker.js:64:11), <anonymous>:241:14)
    at tryCallOne (webpack-internal:///./node_modules/promise/setimmediate/core.js:37:12)
    at eval (webpack-internal:///./node_modules/promise/setimmediate/core.js:123:15)
    at eval (webpack-internal:///./node_modules/react-native/Libraries/Core/Timers/JSTimers.js:1:4804)
    at _callTimer (webpack-internal:///./node_modules/react-native/Libraries/Core/Timers/JSTimers.js:1:2609) 
```

Please note that in the terminal I see 
`GET /508ca35a4baeb9f81480.hot-update.json 200 43 - 0.451 ms` 
However the network panel in the debugger seems to be trying to load hot-update.js

### Expected Behaviour 

Components should be able to hot reload as they do on iOS

### Haul Configuration (webpack.haul.js) 
```const path = require('path');

module.exports = ({ platform, root }, defaults) => ({
  entry: `./index.${platform}.js`,
  resolve: {
    ...defaults.resolve,
    alias: {
      ...defaults.resolve.alias,
      Config: path.join(root, 'config'),
      Components: path.join(root, 'app', 'components'),
      Routes: path.join(root, 'app', 'routes'),
      Util: path.join(root, 'app', 'util'),
      Reducers: path.join(root, 'app', 'reducers'),
    },
  },
  module: {
    ...defaults.module,
    rules: [
      {
        test: /\.js?$/,
        include: '/node_modules/seamless-immutable',
        exclude: '/node_modules/',
        use: [
          {
            loader: 'react-hot-loader/webpack',
          },
        ],
      },
    ].concat(defaults.module.rules || []),
  },
});
```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-beta.13
| react-native     |  0.49.0
| node             |  9.3.0
| npm or yarn      | yarn(1.3.2)

**Comment by ndillon1** [comment]
Update: This issue only occurs when Debugging JS Remotely

**Comment by Krizzu** [comment]
CC @zamotany

**Comment by thymikee** [comment]
@czystyl is this similar to what we face on webpack 4 branch?

**Comment by czystyl** [comment]
Yes, the same problem 😕

**Comment by thymikee** [comment]
Cool, so it's not a regression then and we're good to merge webpack branch

**Comment by czystyl** [comment]
But still need to fix it ;)

**Comment by thymikee** [comment]
Yep, but let's do it as a followup

**Comment by ndillon1** [comment]
@thymikee @czystyl do you have a timeline on when this will be fixed ? Would like to integrate this into my react-native project as soon as possible

**Comment by thymikee** [comment]
@ndillon1 no timeline, but that's a high priority fix.
