### ISSUE TITLE
Fix version numbers

### ISSUE THREAD

**Issue by ShahOfMEC** [callstack/haul#383]
I was going through the version numbers for haul and it didnt make sense to me. I see v1.0.0 was released in June 15, 2017. But then more beta versions of 1.0.0 is being created after that, eg - 1.0.0-beta.0, 1.0.0-beta.1, etc? I believe you would release the beta versions(pre-release) before you release a final version and hence the version numbers for release after 1.0.0 should have been v1.0.1-beta or v1.1.0-beta or v2.0.0-beta. Can this be fixed in next release please?

**Comment by thymikee** [comment]
v1.0.0 was tagged by mistake, I've taken that down. Thanks for pointing that out!

Also it's not available in registry, see: https://yarnpkg.com/en/package/haul
