### ISSUE TITLE
Haul is not bundling when use custom build type on Android

### ISSUE THREAD

**Issue by krystiansliwa** [callstack/haul#392]
Hi, 
yesterday I have encounter problem with bundling Android release version of my app.
It look like haul is not called at all when use custom release build type.

When I call `NODE_ENV=development ./gradlew assembleAppDev` or `NODE_ENV=test ./gradlew assembleAppTest` then haul packager is not bundling at all. When use `NODE_ENV=development ./gradlew assembleRelease` it works.

I am using NODE_ENV to use proper endpoints in webpack but I think this is not a root of the problem.
In other project I used product flavours instead of build types and it also works.

How do you check when to bundle or not. Because it looks like you are bundling only when build type is release?

I have following build types in my build.gradle
```
buildTypes {
    debug {
        debuggable true
        applicationIdSuffix ".dev"
    }
    release {
        minifyEnabled enableProguardInReleaseBuilds
        proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
    }
    appDev {
        initWith release
        applicationIdSuffix ".dev"
    }
    appTest {
        initWith release
        applicationIdSuffix ".test"
    }
}

```
### Haul Configuration (webpack.haul.js)
```
module.exports = ({ platform }, { module, resolve, plugins }) => ({
    entry: `./src/index.ts`,
    module: {
        ...module,
        rules: [
            {
                test: /\.tsx?$/,
                use: [
                    { loader: 'babel-loader' },
                    { loader: 'awesome-typescript-loader' },
                ],
            },
            ...module.rules,
        ],
    },
    resolve: {
        ...resolve,
        extensions: [
            '.ts',
            '.tsx',
            `.${platform}.ts`,
            '.native.ts',
            `.${platform}.tsx`,
            '.native.tsx',
            ...resolve.extensions,
        ],
        alias: {
            'react-native-camera': path.join(
                __dirname,
                'src/helpers/react-native-camera.js',
            ),
        },
    },
    plugins: [
        ...plugins,
        new webpack.DefinePlugin({
            'process.env': {
                NODE_ENV: JSON.stringify(NODE_ENV),
                endpoints: JSON.stringify(endpoints[NODE_ENV]),
            },
        }),
    ],
});
```

### Your Environment
| software         | version
| ---------------- | -------
| Haul             |  1.0.0-beta.11
| react-native     |  0.53.2
| node             | v9.7.1
| yarn      | 1.5.1

**Comment by FredyC** [comment]
In a default `android/app/build.gradle` there is this big commented part. Perhaps you might want to try that? I am not sure if Haul is respecting that settings, but it's a worth the try.

```
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
```

**Comment by krystiansliwa** [comment]
Ok I spend whole day on it and found problem ;). 
For others:
When you are using custom build types or product flavours you need to specify some keys in build.gradle which corresponds to your custom build types.
Here are what you need to add:
```
project.ext.react = [
  root: "../../",
  entryFile: "index.android.js",
  cliPath: "node_modules/haul/bin/cli.js",
  devDisabledInAppDev: true,
  devDisabledInAppTest: true,
  devDisabledInRelease: true,
  bundleInAppDev: true,
  bundleInAppTest: true,
  bundleInRelease: true,
]
```

Summarising problem is not with haul and issue can be closed.

**Comment by krystiansliwa** [comment]
@FredyC Yes now I found that and haul and hauls is respecting that config so it now just works ;)
That's happen when you don't check commented code ;)

**Comment by mohitarora777** [comment]
not working for me

**Comment by aallvi** [comment]
same problem here
