### ISSUE TITLE
Compile source

### ISSUE THREAD

**Issue by thymikee** [callstack/haul#416]
This is obviously better for user experience, and will speed up initial run of Haul with cold cache.

What we need to make it usable for people developing the project:
- [ ] compile on `prepare` hook
- [ ] watch mode for development
- [ ] proper documentation in contributing guide

Since we now use React to render our UI (`next` branch), Haul's internal compilation got a bit slower, so it's about time to make it happen!

**Comment by satya164** [comment]
> compile on `postinstall` hook

compiling on `prepare` hook should do it both before publishing and after install

**Comment by zamotany** [comment]
I'm not sure adding babel dependencies for users just to compile after installing is a good idea

**Comment by satya164** [comment]
@zamotany by after install I mean when you install from local folder with `file:` or install from github. `prepare` won't trigger when installing from registry.
