### ISSUE TITLE
Entry `fs.existsSync` check breaks with custom extensions

### ISSUE THREAD

**Issue by jaredru** [callstack/haul#417]
### Current Behavior
With the new config style, Haul now [tries to verify](https://github.com/callstack/haul/blob/f8fc9e7a74fda0703cec711d6a21c36da1879bea/src/utils/makeReactNativeConfig.js#L335-L339) that the provided entrypoints exist via node path resolution. This breaks support for custom extensions. In our config, we add support for TypeScript, and now our TypeScript-based entrypoints are failing to pass this check.

### Expected Behavior
Haul should rely on Webpack's file resolution instead of node's, enabling custom extensions in entrypoints. When I remove the check locally, building succeeds as expected.

### Haul Configuration (webpack.haul.js)
A simplified example of our config:

```js
...

const config = createWebpackConfig({
    entry: "index.ts",
})(env);

config.resolve.extensions.push(`.${platform}.ts`, ".native.ts", ".ts");

...
```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  v1.0.0-rc.0
| react-native     |  v0.55.3
| node             | v9.11.1
| npm or yarn      | yarn v1.6.0

**Comment by jukben** [comment]
I agree @jaredru we can remove whole check there https://github.com/callstack/haul/blob/next/src/utils/makeReactNativeConfig.js#L322

I will approve your PR if you make a time for it. 💪

**Comment by jukben** [comment]
Fixed, thanks @jaredru 🚀
