### ISSUE TITLE
allow out-of-tree platforms to be dynamically added

### ISSUE THREAD

**Issue by matthargett** [callstack/haul#418]
### Current Behavior
External platforms, such as Windows, cannot use haul without forking it. This is due the platforms array ['android','ios'] being hardcoded in makeReactNativeConfig.

### Expected Behavior
Out-of-tree platforms like Windows, Linux, and MacOS, should be able to use haul without forking haul.
In our initial rn-cli.config PR, we were told the new configuration would allow for out-of-tree platforms, but it turned out not to.

cc @grabbou ,we talked about this back in December and you had a clear idea on how to enable this.

**Comment by jukben** [comment]
This could be closed, am I right, @acoates-ms? 💪
