### ISSUE TITLE
Haul crashes trying to make a TTY adapter when run via child_process.spawn

### ISSUE THREAD

**Issue by msluther** [callstack/haul#420]
### Current Behavior
If haul is spawned with `require('child_process').spawn` it attempts to create a TTY session, which throws and fails out causing packaging not to run.

### Expected Behavior
It should be able to either:
1. Fallback to previous behavior (prior to RC0) where no TTY session was used, or
2. Provide a CLI option to opt out of the TTY session

I can work around the issue by forcing haul into test mode by spawning with the `NODE_ENV` set to test, but that's not really an appropriate work around.

```js
require('child_process').spawn('npx', args, {
  env: Object.assign({}, process.env, { NODE_ENV: 'test' })
});
```

https://github.com/callstack/haul/blob/v1.0.0-rc.0/src/server/ui.js#L72

**Comment by thymikee** [comment]
We plan to release a node API so you don't need to spawn the process manually. Thanks for posting a workaround though!

**Comment by zamotany** [comment]
As @thymikee said, Haul node API will be a way to go. However before that once the new version of `react-slate` comes out, Haul won't crash.

**Comment by zamotany** [comment]
@msluther Can you install haul from `next` branch and check if the issue still occurs?? It should be fixed with https://github.com/callstack/haul/pull/427

**Comment by msluther** [comment]
@zamotany Sorry for the delay, I was finally able to get this tested out with `^1.0.0-rc.10` and everything seems to be working when run from a child_process spawn now.  Thanks all!
