### ISSUE TITLE
 Error: invalid stored block lengths

### ISSUE THREAD

**Issue by sky-franciscogoncalves** [callstack/haul#439]
### Current Behavior
Haul crashes, when I import or require a specific npm private library on a Lerna package that is a dependency of a react-native project.

```error Command failed with exit code 1.```

stderr.log shows the following info:
 ```
{ Error: invalid stored block lengths
    at InflateRaw.zlibOnError (zlib.js:153:15) errno: -3, code: 'Z_DATA_ERROR' }
```

### Expected Behavior
The private library would be loaded as it is happening with other private libraries I'm using.

### Haul Configuration (webpack.haul.js)
```
{
    devtool: 'eval-source-map',
    module: {
      ...module,
      rules: [
        ...module.rules,
        { test: /\.(graphql|gql)$/, exclude: /node_modules/, loader: 'graphql-tag/loader' },
        { test: /\.(ts|tsx)?$/, loaders: ['babel-loader', 'ts-loader'] },
        {
          test: /\.js?$/,
          include: [/node_modules\/@shoutem/, /node_modules\/react-native-vector-icons/],
          use: [{ loader: 'babel-loader' }],
        },
      ],
    },
    resolve: {
      ...resolve,
      modules: [path.resolve(__dirname), 'node_modules'],
      extensions: ['.ts', '.tsx', '.ios.tsx', '.android.tsx', ...resolve.extensions],
      alias: { ...resolve.alias, 'react-native': path.resolve(__dirname, 'node_modules/react-native') },
    },
  }
```
### My Environment

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-rc.0
| react-native     |  0.55.3
| node             | 8.9.1
| yarn      | 1.3.2

Thanks for your help.

**Comment by thymikee** [comment]
This should be fixed on `next` branch. PR for reference: https://github.com/callstack/haul/pull/434
I'll try to schedule a release today with the fix :)

**Comment by sky-franciscogoncalves** [comment]
Thanks!
