### ISSUE TITLE
Deprecated style of the configuration

### ISSUE THREAD

**Issue by yvasiuk-sphere** [callstack/haul#446]
After running 'yarn haul' I see configuration deprecation warning

### Current Behavior
1. run 'yarn haul'
2. see output "WARN You using a deprecated style of the configuration. Please follow the docs for the upgrade. See https://github.com/callstack/haul/blob/master/docs/Configuration.md"

### Expected Behavior
1. run 'yarn haul'
2. see no deprecation warnings in the console output

### Haul Configuration (webpack.haul.js)
```
const path = require('path');

module.exports = ({ root }, defaults) => ({
  entry: './index.js',
  resolve: {
    ...defaults.resolve,
    alias: {
      ...defaults.resolve.alias,
      actions: path.join(root, 'src', 'actions'),
      api: path.join(root, 'src', 'api'),
      assets: path.join(root, 'src', 'assets'),
      components: path.join(root, 'src', 'components'),
      config: path.join(root, 'src', 'config'),
      containers: path.join(root, 'src', 'containers'),
      locales: path.join(root, 'src', 'locales'),
      models: path.join(root, 'src', 'models'),
      navigators: path.join(root, 'src', 'navigators'),
      reducers: path.join(root, 'src', 'reducers'),
      store: path.join(root, 'src', 'store'),
      utils: path.join(root, 'src', 'utils')
    }
  }
});
```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-rc.4
| react-native     |  0.55.4
| node             | 10.5.0
| npm or yarn      | 6.1.0

**Comment by thymikee** [comment]
Looks like we link to `master` instead of `next`. See: https://github.com/callstack/haul/blob/next/docs/Configuration.md
cc @jukben
