### ISSUE TITLE
App crashes when trying to debug JS remotely

### ISSUE THREAD

**Issue by matotim** [callstack/haul#471]
### Current Behavior
On iOS, when I open the Developer menu and I click on "Debug JS Remotely", the app reloads but then crashes with those 2 errors : 
`Module RCTLog is not a registered callable module (calling logIfNoNativeHook)`
`Module RCTDeviceEventEmitter is not a registered callable module (calling emit)`

I noticed that the app tries to load an `index.delta`, which may explain why it crashes ?

### Expected Behavior
I expect the app to reload and to be able to debug my JS code inside my browser (Chrome).

### Haul Configuration (webpack.haul.js)
```
import { createWebpackConfig } from "haul";

export default {
  webpack: createWebpackConfig(({ platform }) => ({
    entry: `./index.js`
  }))
};
```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-rc.7
| react-native     |  0.55.2
| node             | 8.4.0
| npm or yarn      | 5.3.0

**Comment by zamotany** [comment]
No longer an issue with revamped version of Haul on `next` branch.

**Comment by conor909** [comment]
Im getting this today on RN 60.5

**Comment by conor909** [comment]
Im getting this today on "react-native": "0.61.5"

**Comment by zamotany** [comment]
@conor909 What version of `@haul-bundler/cli` are you using?

**Comment by conor909** [comment]
Sorry Im not sure what `callstack/haul` is, I posted in the wrong repo.  Must be a React-Native issue
