### ISSUE TITLE
MP4 files in assets resolved to wrong android folders structure

### ISSUE THREAD

**Issue by OleksandrKucherenko** [callstack/haul#472]
### Current Behavior
one of reactive-native modules introduce MP4 assets, during bundle operation MP4 file place into `drawable-*` folder. 

### Expected Behavior
MP4 files are not allowed in `res/drawable-*` folders, it should be placed into `res/raw` folder.

### Haul Configuration (webpack.haul.js)
default

### Your Environment

Mac OS

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-rc.7
| react-native     |  0.55.4
| node             | 8.11.3
| npm or yarn      | yarn 1.6

**Comment by thymikee** [comment]
Happy to accept PR fixing that :)

**Comment by OleksandrKucherenko** [comment]
https://github.com/callstack/haul/pull/476
