### ISSUE TITLE
Can't release application with latest haul

### ISSUE THREAD

**Issue by befront** [callstack/haul#487]
### Current Behavior
Unhandled JS Exception: undefined is not an object (evaluating 'r("./node_modules/react-hot-loader/patch.js").default.disableProxyCreation=!0')

### Expected Behavior
No errors

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-rc.8
| react-native     |  0.57.2
| node             | v9.11.1
| npm or yarn      | yarn 1.6.0

**Comment by zamotany** [comment]
We are aware of this issue. The reason it is happening is that out `hot/patch.js` file is included in production build here:
https://github.com/callstack/haul/blob/next/src/utils/makeReactNativeConfig.js#L388

If anyone is interested in contributing, this file should be applied conditionally based on `dev` flag from here: https://github.com/callstack/haul/blob/next/src/utils/makeReactNativeConfig.js#L77

**Comment by zamotany** [comment]
Should be fixed in #488

**Comment by marchaos** [comment]
Still seeing this error on the latest version.
