### ISSUE TITLE
`makeHot` needs to return same value with same params

### ISSUE THREAD

**Issue by bradennapier** [callstack/haul#490]
### Current Behavior

`makeHot`'s call result will ALWAYS return a different value.  This is a problem because it means that every little change will re-render the whole app when you want to enable hot reloading.  

In the case of `react-navigation` I was confused as-to why every time i toggled the drawer my entire screen was refreshing.  After many hours I finally realized it was due to `makeHot`.

This occurs because in the `makeHot` function the all of the function is creating a new React Component every time rather than returning the same one.  

See #491 for the PR to fix.

```javascript
const getHome = () => HomeView;

console.log(makeHot(getHome, 'Home')() === makeHot(getHome, 'Home')());
```

Since the above returns `false` it means that calling `makeHot` function is not returning the same value every time it is called - thus everything re-renders completely any time `getScreen` is called by `react-navigation`.

### Expected Behavior

```javascript
makeHot(() => HomeView, 'Home')() === makeHot(() => HomeView, 'Home')()
```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-rc.9
| react-native     |  0.57.3
| node             |  10.12.0
| npm or yarn      | yarn

**Comment by zamotany** [comment]
With `@haul-bundler/cli` we no longer support HMR due to various problems and issues, which we don't have a capacity to handle.
