### ISSUE TITLE
Feature Haul on Docusaurus?

### ISSUE THREAD

**Issue by ellereeeee** [callstack/haul#497]
Hello,

May I feature Haul on Docusaurus's [user page](https://docusaurus.io/en/users)? This will give Haul recognition as well as show others creative ways to use Docusaurus.

If you give me your permission, could you also please provide me a file of Haul's logo (preferrably SVG)? It should not exceed 512x512.

I the saw logo on Haul's Github's page, but I would need a logo with just the cardboard box logo and not the text "Haul". Thank you for your time!

**Comment by thymikee** [comment]
Sounds awesome! 
@satya164 @grabbou do you have the source of the icon?

**Comment by ellereeeee** [comment]
My pull request to add Haul was merged. You can check it out [here](https://docusaurus.io/en/users).

Thanks again!
