### ISSUE TITLE
Cannot find module react-dom

### ISSUE THREAD

**Issue by rodineijf** [callstack/haul#508]
### Current Behavior

Steps to reproduce:

react-native init MyProject
yarn add --dev haul
yarn haul init
yarn haul start --platform ios

  ERROR
./node_modules/haul/node_modules/react-hot-loader/dist/react-hot-loader.development.js
Module not found: Error: Can't resolve 'react-dom' in '/Users/rfagundes/Workspace/rn/haulApp/node_modules/haul/node_modules/react-hot-loader/dist'

### Haul Configuration (webpack.haul.js)

Supposed to be haul.config.js?

```
import { createWebpackConfig } from "haul";

export default {
  webpack: createWebpackConfig(({ platform }) => ({
    entry: `./index.js`
  }))
};
```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-rc.10
| react-native     |  0.57.8
| node             |  10.14.2
| npm or yarn      | yarn 1.12.3

**Comment by luigiplr** [comment]
Looks like [react-hot-loader](https://github.com/gaearon/react-hot-loader) has imported `"react-dom"` since [4.5.0](https://github.com/gaearon/react-hot-loader/releases/tag/4.5.0) I fixed this locally by installing version `4.4.0`.


```bash
yarn add react-hot-loader@4.4.0
#OR
npm install react-hot-loader@4.4.0
```

**Comment by rodineijf** [comment]
Thanks @luigiplr 

I fixed installing react-hot-loader and react-dom as dependencies.

**Comment by CrazzzyDev** [comment]
@rodineijf Thanks. Your solution works.
Can you please explain, why react-hot-loader depends on "react-dom" for React Native projects? Would it works when we release a build with it?
