### ISSUE TITLE
iOS Bundle Isn't Output to Product.app Folder

### ISSUE THREAD

**Issue by chevonc** [callstack/haul#509]
When building for release in iOS, XCode seems to runt he haul `cli` command with the right args, but there's no output file. If I run this command myself from the terminal, it works as expected.
 
Example of command

```

node node_modules/haul/bin/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output /Volumes/Data/code/myApp/client/www/native_v2/ios/build/Build/Products/Release-iphonesimulator/myApp.app/main.jsbundle --assets-dest /Volumes/Data/code/myApp/client/www/native_v2/ios/build/Build/Products/Release-iphonesimulator/myApp.app

```
### Current Behavior
The bug here is that by `main.jsbundle` file is not output to to the `ios/build/Build/Products/Release-iphonesimulator/myApp.app/` folder

### Expected Behavior
`main.jsbundle` is output to `ios/build/Build/Products/Release-iphonesimulator/myApp.app` drop so that the app can run in release mode

### Haul Configuration (webpack.haul.js)
I'm using the default config

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  1.0rc^10
| react-native     |  0.57.8
| node             |  8.9
| npm or yarn      |  yarn

**Comment by chevonc** [comment]
Here's an example of the xcode shell script output - 
![image](https://user-images.githubusercontent.com/684657/50878113-ee3e0500-1389-11e9-9f34-93baa0882017.png)

I can workaround this by manually adding a `main.jsbundle` file to`ios/myApp` but it wouldn't get updated each build.

Any thoughts of what's causing this?

**Comment by zamotany** [comment]
This should not be happening with the new `@haul-bundler/cli`. If anyone is having problems please open a new issue.
