### ISSUE TITLE
A lot ot "hot-update" files being generated

### ISSUE THREAD

**Issue by zaguiini** [callstack/haul#513]
### Current Behavior
Whenever I run the app, a lot of `hot-update.(json|js)` files are generated and they remain there after closing the app/bundler. **I am not even using hot reload. It's turned off on Dev Settings**

I can add them to `.gitignore` via `*.hot-update.*` and it's a "solution", but not ideal...

![image](https://user-images.githubusercontent.com/26530524/51603367-c35ac180-1ef0-11e9-9434-0d0beeb8dcac.png)

### Expected Behavior
No clutter. Or at least in another folder.

### Haul Configuration (webpack.haul.js)
```js
import {createWebpackConfig} from "haul";
import { resolve } from 'path'

export default {
  webpack: env => {
    const config = createWebpackConfig({
      entry: `./src/index.ts`,
    })(env);

    config.module.rules = [
      {
        test: /\.tsx?$/,
        exclude: '/node_modules/',
        use: [
          {
            loader: 'babel-loader',
          },
          {
            loader: 'ts-loader',
          }
        ]
      },
      ...config.module.rules,
    ];

    config.resolve.extensions = [
      '.ts',
      '.tsx',
      `.${env.platform}.ts`,
      '.native.ts',
      `.${env.platform}.tsx`,
      '.native.tsx',
      ...config.resolve.extensions,
    ]

    config.resolve.alias = {
      ...config.resolve.alias,
      src: resolve(__dirname, 'src'),
    }

    return config;
  }
};
```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-rc.11
| react-native     |  0.57.8
| node             | v10.15.0
| npm or yarn      | 1.13.0

**Comment by thymikee** [comment]
This is due to this change: https://github.com/callstack/haul/pull/512

We could move the updates to some temp directory (see: https://github.com/callstack/haul/pull/512/files#diff-99e77f1c262ae763f3d7d593b2c0b417R85), and provide a way to clean it up. 
Anybody willing to work on a solution?

**Comment by apexskier** [comment]
Here's a proposed fix for this - https://github.com/callstack/haul/pull/516

**Comment by sirajulm** [comment]
@apexskier  Thanks. This have fixed random folders being created. But the `documentation` for the `start` command is not updated with the new `--assetDest` option.

**Comment by thymikee** [comment]
Mind sending a PR? :)
