### ISSUE TITLE
Is there a way to enable logging to file?

### ISSUE THREAD

**Issue by sayzenberg** [callstack/haul#523]
I'm currently working on integrating Haul into a project, and it's working great so far. However, one issue I'm running into is that I need to be able to measure performance data, such as live reload times, in order to track and process them elsewhere. This is something that I see came up in #343 , but as far as I can tell the changes discussed have not yet been made. I'd settle for manually parsing the CLI output, but I can't seem to get anything from stdout, and node_modules/.haul-artifacts/stdout.log is completely empty at all times. I'd really like to avoid just piping all output to file, because this needs to be captured concurrently with CLI use, and for some reason tee seems to suppress CLI updates.

Am I missing something obvious, or is this scenario currently not possible?

**Comment by thymikee** [comment]
Cc @zamotany

**Comment by hjhart** [comment]
I'd love to extend haul's logging abilities. Currently it all goes through the `https://github.com/callstack/haul/blob/next/src/server/ui.js` file, which subscribes to an EventEmitter.

It would be pretty straightforward to write another logger that subscribes to the EventEmitter as well.

My interests lie in that I'd love to have a more CI friendly (or `foreman start` friendly) logging available within the context of `haul start`. It all happens in a very `ncurses` manner right now, which is sub-optimal in some applications.

Curious to hear what contributors think about this – I may be able to put together a pull request. I've been looking at this code a lot lately!

**Comment by thymikee** [comment]
PRs welcome :)

**Comment by zamotany** [comment]
If anyone is interested:
Yes, there's a option to enable logging to file with `--output-file <filename>` and `--json`, which will write logs in JSON format. #628 will also improve the logging to file.

The recommended way to log to file on CI:
* `haul bundle --output-file ./bundle.log --json <...rest>`
* `haul start --output-file ./start.log --json --no-interactive <...rest>`
