### ISSUE TITLE
release build don't  work right after remove haul

### ISSUE THREAD

**Issue by cani1see** [callstack/haul#566]
I installed package "haul" and remove it.
at that time the error already came up,

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'PATH/node_modules/haul/bin/cli.js'
```

I did the sequence 
```
rm -rf node_modules
watchman watch-del-all
rm -rf $TMPDIR/react-*
rm -rf $TMPDIR/metro-*
rm -rf $TMPDIR/haste-*
npm start -- --reset-cache
```

and the problem is gone.

today I try to build a release package, and the problem is back.

only this time it happens in :app:bundleReleaseJsAndAssets stage only.

I tried a lot of things: remove yarn cache, switch to npm to manage node_modules, switch node version..

this time it won't fix.

I can't even find the string "haul" in my project.

**Comment by tido64** [comment]
Did you remove Haul completely from `package.json`? Does your `build.gradle` files reference Haul in any way? How do you otherwise build your bundle?

**Comment by cani1see** [comment]
@tido64 
found it 
```
project.ext.react = [
  cliPath: "node_modules/haul/bin/cli.js"
]
```
 is still in `build.gradle`, don't know why text find didn't spot it.

**Comment by tido64** [comment]
Glad you found it 😄
