### ISSUE TITLE
react-spring cannot resolve 'react-native'

### ISSUE THREAD

**Issue by natew** [callstack/haul#572]
## Environment

Using rc.13 and react-spring/native

## Description

When importing `` I get this error on startup:

```
Module not found: Error: Can't resolve 'react-native' in '/Users/nw/projects/motion/orbit/node_modules/react-spring'
```

## Reproducible Demo

```
react-native init myproject
cd myproject
haul init
yarn add react-spring
```

and then in App.js:

```
import { animated } from 'react-spring'
```

As you'll see it has a `react-native` entrypoint in package.json:

`"react-native":"native.js"`

And this file expects react-native, which for some reason isn't being found. I've actually been trying to modify my haul.config.js webpack config without much luck, separately I had tried adding a css ignore with:

```
export default {
  webpack: env => {
    const config = createWebpackConfig({
      entry: './index.js',
    })(env)

    config.module.rules = [
      ...config.module.rules,
      {
        test: /\.css$/,
        use: 'ignore-loader',
      },
    ]

    return config
  },
}
```

But that isn't working for whatever reason, so I'm not sure, but I also tried applying this:

```
    config.resolve.alias = {
      ...config.resolve.alias,
      'react-native': join(__dirname, 'node_modules/react-native'),
    }
```

And not sure if it's being applied as my css one isn't, but that one too isn't getting picked up. Don't want to confuse things too much in the case my configuration isn't working. It does seem to pick up the config, if I put an invalid entry it complains.

**Comment by zamotany** [comment]
@natew 

This code:
```js
config.module.rules = [
      ...config.module.rules,
      {
        test: /\.css$/,
        use: 'ignore-loader',
      },
    ]
```
looks fine to me as well as:
```
config.resolve.alias = {
      ...config.resolve.alias,
      'react-native': join(__dirname, 'node_modules/react-native'),
    }
```

Can you run `yarn list --pattern react-native` and paste the output?

**Comment by zamotany** [comment]
If anyone is having this issue please use `@haul-bundler/cli` (if not already using) and feel free to open a new issue.
