### ISSUE TITLE
[@haul-bundler/0.5.0] glamorous-native module parse error

### ISSUE THREAD

**Issue by Mayzie** [callstack/haul#577]
## Environment

- "react-native": "0.59.2",
- "@haul-bundler/babel-preset-react-native": "^0.5.0-alpha.1",
- "@haul-bundler/cli": "^0.5.0-alpha.1",
- "@haul-bundler/preset-0.59": "^0.5.0-alpha.1",

## Description

Haul is unable to compile a bundle due to me using the [glamorous-native](https://github.com/robinpowered/glamorous-native) package. It produces the following error:

````
GET /status 200
  info ▶︎ Compiling bundle "index" for platform ios
  er▶︎r(undefined) ./node_modules/glamorous-native/src/with-theme.js 12:10
       Module parse failed: Unexpected token (12:10)
       You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
       | export default function withTheme(ComponentToTheme) {
       |   class ThemedComponent extends React.Component {
       >     state = {theme: {}}
       |     setTheme = theme => this.setState({theme})
       |
        @ ./node_modules/glamorous-native/src/index.js 4:0-36 52:0-33
````
(note: I also disabled the hijackConsole() function in `server/Server.js`, otherwise it just spammed the console with warnings and resulted in an overflow, but that's a separate issue)

It appears as if the Webpack loader used by default in Haul cannot compile certain JavaScript files that the Metro Bundler has no trouble loading? Simply importing glamorous-native and using it produces the above error:

```javascript
import g from 'glamorous-native';

...
render() {
  <Container />
}
...

const Container = g.view({
  flexDirection: 'column',
});
```

**Comment by thymikee** [comment]
I think Haul still doesn't transpile the source code of node_modules by default (only some common ones are included, like starting with `react-native-` etc). You'll need to adjust `babel-loader` configuration to include `glamorous-native`, which recently got revamped, more details here: https://github.com/callstack/haul/pull/570 and in related issue

**Comment by zamotany** [comment]
This line https://github.com/callstack/haul/blob/next/packages/haul-preset-0.59/src/defaultConfig.ts#L49 is only allowing certain modules to be transpiled from `node_modules`. Ideally we would have an option in the `haul.config.js` to include paths/libaries to transpile manually, but for now you need to use `transform` and overwrite that regex to add `glamorous-native`. The reason we don't transpile all `node_modules` is that Webpack is nowhere near as fast as Metro, so we just try to minimise the damage (long build times) whenever we can.

**Comment by Mayzie** [comment]
Terrific. Just modified that line and it now transpiles. Thanks guys! 🙂
