### ISSUE TITLE
Remote debugging not working on VSCode (next branch)

### ISSUE THREAD

**Issue by koke** [callstack/haul#600]
## Environment

```
$ yarn list --pattern=haul
yarn list v1.16.0
├─ @haul-bundler/babel-preset-react-native@0.8.0
├─ @haul-bundler/basic-bundle-webpack-plugin@0.8.0
├─ @haul-bundler/cli@0.8.0
├─ @haul-bundler/core-legacy@0.8.0
├─ @haul-bundler/core@0.8.0
├─ @haul-bundler/inspector-events@0.8.0
├─ @haul-bundler/preset-0.60@0.8.0
└─ @haul-bundler/ram-bundle-webpack-plugin@0.8.0
```

## Description

Using the [vscode-react-native](https://marketplace.visualstudio.com/items?itemName=vsmobile.vscode-react-native) extension for debugging instead of Chrome doesn't work in the `next` branch.

The first issue is that the extension can't find the debugger code in the standard path:

```
Could not debug. {"statusCode":404,"error":"Not Found","message":"File /debugger-ui/debuggerWorker.js not found"}
```

Luckily, there's a configuration option for that which fixes this one:

```"debuggerWorkerUrlPath": "haul_assets/"```

After fixing that, I get the following error:

```
Error: {"statusCode":404,"error":"Not Found","message":"File /abort-controller.js.map not found"}. Debugging won't work: Try reloading the JS from inside the app, or Reconnect the VS Code debugger: Couldn't import script at <http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false> (error code 1408)
```

It looks like some of the React Native dependencies have a [relative `sourceMappingURL`](https://unpkg.com/abort-controller@3.0.0/dist/abort-controller.js) that won't work when included in the bundle. Using [source-map-loader](https://github.com/webpack-contrib/source-map-loader) seems to get around this issue with the following config:

```
import { withPolyfills, makeConfig } from "@haul-bundler/preset-0.60";

export default makeConfig({
  bundles: {
    index: {
      entry: withPolyfills('./index.js'),
      transform({ bundleName, env, runtime, config }) {
        config.module.rules = [
          ...config.module.rules,
          {
            test: /\.js$/,
            use: ["source-map-loader"],
            enforce: "pre"
          }
        ];
      },
    },
  },
});
```

The last problem I found that I wasn't able to solve yet:

```
Error: Cannot detect platform from URL: /Users/koke/a8c/gutenberg-mobile/.vscode/.react/index.bundle
    at DebuggerWorker.getPlatformFromURL (/Users/koke/a8c/gutenberg-mobile/.vscode/.react/debuggerWorker.js:204:13)
    at DebuggerWorker.executeApplicationScript (/Users/koke/a8c/gutenberg-mobile/.vscode/.react/debuggerWorker.js:217:28)
    at DebuggerWorker.processMessage (/Users/koke/a8c/gutenberg-mobile/.vscode/.react/debuggerWorker.js:255:15)
    at DebuggerWorker.handleMessage (/Users/koke/a8c/gutenberg-mobile/.vscode/.react/debuggerWorker.js:285:12)
    at onmessage (/Users/koke/a8c/gutenberg-mobile/.vscode/.react/debuggerWorker.js:293:12)
    at process.<anonymous> (/Users/koke/a8c/gutenberg-mobile/.vscode/.react/debuggerWorker.js:67:9)
    at process.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Relevant bit in the debug logs for the extension:

> `Script http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false downloaded to /Users/koke/a8c/gutenberg-mobile/.vscode/.react/index.bundle`

It seems like `debuggerWorker.js` is trying to extract the platform from the URL, but the vscode extension is caching the bundle and stripping the URL query from the filename.

I'm not sure where it's best to fix this, but debugging was working on master (with [some tweaks](https://github.com/Microsoft/vscode-react-native/blob/master/doc/debugging.md#debugging-with-typescript-and-haul))

## Reproducible Demo

I uploaded a sample blank project [haulnextvscode.zip](https://github.com/callstack/haul/files/3403087/haulnextvscode.zip) generated with the following steps:

1. react-native init haulnextvscode
2. cd haulnextvscode
3. yarn add --dev @haul-bundler/cli @haul-bundler/preset-0.60 @haul-bundler/babel-preset-react-native (I had to add this manually even if the documentation doesn't mention it)
4. yarn haul init
5. yarn haul start
6. code --install-extension msjsdiag.vscode-react-native
7. code .
8. Follow the instructions on the extension to set up debugging.

Open Visual Studio code on the checkout and install the "React Native Tools" extension. Switch to the debugger and run the 'Attach to debugger' configuration. Then enable remote debugging in the app from the developer menu.

**Comment by zamotany** [comment]
I think I can get away with checking the platform, since it's needed for multi-bundle, but the multi-bundle is not yet part of the RN.

**Comment by koke** [comment]
Thanks. Unrelated to viscose, but is there any reason not to use `source-map-loader` in the default config?

**Comment by zamotany** [comment]
@koke I wasn't 100% sure what `source-map-loader` does and if we need it, but after reading more about it, I think we can add it. Would you mind creating a PR to add it to `preset-0.59` and `preset-0.60` in `defaultConfig.ts`??

**Comment by koke** [comment]
In my latest attempt, I wasn't able to make `source-map-loader` work as expected for debugging dependencies, or maybe our dependencies had source maps built the wrong way. I can do the PR once I have a bit more clarity on what's going on there.
