### ISSUE TITLE
@haul-bundler runtime.logger.debug is not function

### ISSUE THREAD

**Issue by tkow** [callstack/haul#602]
### npm dependencies 
```json
 {
    "@types/typescript": "^2.0.0",
    "@types/webpack-merge": "^4.1.5",
    "babel-loader": "^8.0.6",
    "react": "^16.8.6",
    "react-native": "0.60.3",
    "ts-loader": "^6.0.4",
    "typescript": "^3.5.3",
    "webpack-merge": "^4.2.1"
},
```

### Error Log
```
/build/webpack/reso
lvers/AssetResolver.js:97
        runtime.logger.debug(`Reso
lved file: ${request.path} <--> ${
resolvedFile.path}`);


TypeError: runtime.logger.debug is
 not a function
    at resolver.fileSystem.readdir
```

## Description

haul with typescript cause error runtime doesn't have logger.debug with transform option. Does anyone have an idea why this occur.

## Reproducible Demo

reproduce by https://github.com/tkow/haul-test
this repository configuration works  at previous version of react-native and haul@1.0.0-rc.15

**Comment by zamotany** [comment]
@tkow It should be fixed now and will be released today EOD.

**Comment by tkow** [comment]
Thank you for very quick fix!
I survey this and this doesn't occur when I avoid to use smartMerge and keep modules refs by no modifications.

```typescript
config.resolve.extensions = config.resolve.extensions.concat(addConfig.resolve.extensions)
config.module.rules = config.module.rules.concat(addConfig.module.rules)
```

So I think this problem could be caused by reference lost though I'm not certain. I'll be glad to hear If this is cared next release.

**Comment by zamotany** [comment]
`smartMerge` probably was loosing a reference since the `logger` there was a `Proxy`. I switched it to built-in proxy support in logger so the `smartMerge` is handling it properly.
