### ISSUE TITLE
`haul start --port` not being used

### ISSUE THREAD

**Issue by hesyifei** [callstack/haul#607]
## Environment

```
$ react-native --version
react-native-cli: 2.0.1
react-native: 0.60.4
$ yarn haul --version
yarn run v1.17.3
$ haul start --version
0.9.0
✨  Done in 1.16s.
```

## Description

Command: `yarn haul start --port 3030` (https://github.com/callstack/haul/blob/64802a6174b4949c999397673af58ed1ad59ebe1/docs/CLI%20Commands.md#haul-start)

Expected behavior: `haul` should start on port 3030 and we should be able to open http://localhost:3030/.

Actual behavior: `haul` started on the default port 8081.

<img width="585" alt="Screen Shot 2019-07-19 at 12 18 10 PM" src="https://user-images.githubusercontent.com/4939421/61559848-8b57b580-aa1f-11e9-8322-9c602c93978c.png">

Similarly, `yarn haul start --no-interactive true` also doesn't work. It still displays the UI.

## Reproducible Demo

`next` branch

```
react-native init MyProject
cd MyProject
yarn add --dev @haul-bundler/cli
yarn haul init
yarn haul start --port 3030
```
I have also tried `yarn haul start --port=3030` and that doesn't work too.

**Comment by zamotany** [comment]
The bug is fixed and will be released soon.

**Comment by hesyifei** [comment]
@zamotany, thanks! `yarn haul start --no-interactive true` seems to be ignored too. It might be the same problem.

**Comment by zamotany** [comment]
For now use `--no-interactive=true`. For some reason yargs is not properly handling this option. I'll look into it.

**Comment by zamotany** [comment]
@hesyifei you might want to check #611
