### ISSUE TITLE
Issue with Typescript React Native setup

### ISSUE THREAD

**Issue by arundilipan** [callstack/haul#612]
## Environment

Running this on macOS 10.14.5.

- `npm`: `6.9.0`
- `node`: `12.6.0`
- `react-native`: `0.60.4`
- `react-native-cli`: `2.0.1`

## Description

Package is not building on `yarn start haul`, getting an error that looks like in the terminal:
```
Field 'browser' doesn't contain a valid alias configuration
```

## Reproducible Demo

- Created new project using `react-native init Project --template typescript`
- Added `haul` using `yarn add --dev @haul-bundler/cli`
- Initialized `haul` using `yarn haul init`
- Ran `haul` using `yarn haul start`
- Ran simulator using `react-native run-ios`

**Comment by zamotany** [comment]
@arundilipan Can you copy & paste content of `haul.config.js`?

**Comment by isuhar** [comment]
Similar problem with TypeScript

export default makeConfig({
    bundles: {
        index: {
            entry: "./src/mobile/index",
            transform({ bundleName, env, runtime, config }) {
                runtime.logger.info(`Altering Webpack config for bundle ${bundleName}`)

                const options = makeOptions(Object.assign({}, argv.env, argv, {mobile: true}, env, {prod: !env.dev}))

                if (env.dev) {
                    spliceFilter(config.entry, entry => entry.indexOf("hot/patch.js") !== -1)
                    spliceFilter(config.plugins, plugin => plugin instanceof HotModuleReplacementPlugin)
                    config.resolve.alias = {}
                } else {
                    spliceFilter(config.plugins, plugin => plugin instanceof SourceMapDevToolPlugin)
                }

                config = merge.strategy({
                    "module.rules": "replace",
                    "stats": "replace"
                })(
                    config,
                    resolver(options)
                )
            },
        },
    },
})

![image](https://user-images.githubusercontent.com/5614087/61861713-2bf11e00-aed5-11e9-897e-925c33bccdea.png)

**Comment by zamotany** [comment]
@isuhar 
Try adding this to `transform`:
```
config.resolve.extensions = [
  '.ts',
  '.tsx',
  `.${env.platform}.ts`,
  '.native.ts',
  `.${env.platform}.tsx`,
  '.native.tsx',
  ...config.resolve.extensions,
]
```
If that's the cause, I think I'll add it to a default config.

**Comment by arundilipan** [comment]
> @arundilipan Can you copy & paste content of `haul.config.js`?

tried this:
```js
import { withPolyfills, makeConfig } from "@haul-bundler/preset-0.60";

export default makeConfig({
  bundles: {
    index: {
      entry: withPolyfills('./index.js'),
    },
  },
});
```

then I basically did this
```js
export default makeConfig({
  bundles: {
    index: {
      entry: withPolyfills('./index.js'),
      transform({ env, config }) {
        config.module.rules = [
          {
            test: /\.tsx?$/,
            loader: 'ts-loader'
          },
          ...config.module.rules,
        ];
         config.resolve.extensions = [
          '.ts',
          '.tsx',
          `.${env.platform}.ts`,
          '.native.ts',
          `.${env.platform}.tsx`,
          '.native.tsx',
          ...config.resolve.extensions,
        ]
      },
    },
  },
});

```

**Comment by isuhar** [comment]
@zamotany 
`
{ mode: 'development',
  context: '/home/igor/www/megaplan/front',
  devtool: false,
  entry: [ './src/mobile/index' ],
  output:
   { path: '/tmp/haul-start-4GyFWM',
     publicPath: 'http://localhost:8081/',
     globalObject: 'this',
     filename: 'index..bundle' },
  module:
   { rules: [ [Object], [Object], [Object], [Object], [Object] ],
     noParse:
      [ /google-libphonenumber\/dist\/browser\/libphonenumber\.js$/ ] },
  plugins:
   [ CaseSensitivePathsPlugin { options: {}, pathCache: {}, fsOperations: 0, primed: false },
     DefinePlugin { definitions: [Object] },
     LoaderOptionsPlugin { options: [Object] },
     SourceMapDevToolPlugin {
       sourceMapFilename: '[file].map',
       sourceMappingURLComment: '\n//# sourceMappingURL=[url]',
       moduleFilenameTemplate: '[absolute-resource-path]',
       fallbackModuleFilenameTemplate: 'webpack://[namespace]/[resourcePath]?[hash]',
       namespace: '',
       options: [Object] },
     WebpackBasicBundlePlugin { bundle: false, sourceMap: true, preloadBundles: [] },
     IgnoreWarningsPlugin { patterns: [Array] },
     DefinePlugin { definitions: [Object] },
     ProvidePlugin { definitions: [Object] },
     ForkTsCheckerWebpackPlugin {
       startAt: 0,
       computeContextPath: [Function],
       options: [Object],
       tsconfig: './tsconfig.json',
       compilerOptions: {},
       tslint: '/home/igor/www/megaplan/front/tslint.mobile.json',
       tslintAutoFix: false,
       watch: [],
       ignoreDiagnostics: [],
       ignoreLints: [],
       ignoreLintWarnings: false,
       reportFiles: [],
       logger: [Console],
       silent: false,
       async: true,
       checkSyntacticErrors: true,
       workersNumber: 1,
       memoryLimit: 2048,
       useColors: true,
       colors: [Chalk],
       formatter: [Function: defaultFormatter],
       tsconfigPath: undefined,
       tslintPath: undefined,
       watchPaths: [],
       compiler: undefined,
       started: undefined,
       elapsed: undefined,
       cancellationToken: undefined,
       isWatching: false,
       checkDone: false,
       compilationDone: false,
       diagnostics: [],
       lints: [],
       emitCallback: [Function: noopEmitCallback],
       doneCallback: [Function: doneCallback],
       typescriptPath:
        '/home/igor/www/megaplan/front/node_modules/typescript/lib/typescript.js',
       typescript: [Object],
       typescriptVersion: '3.3.3333',
       tslintVersion: '5.13.0',
       useTypescriptIncrementalApi: true,
       vue: false,
       measureTime: false },
     CollectMessagesPlugin { collector: [Collector] } ],
  resolve:
   { plugins: [ [HasteResolver], [AssetResolver] ],
     mainFields: [ 'react-native', 'browser', 'main' ],
     extensions:
      [ '..js',
        '.native.js',
        '.js',
        '.ts',
        '.tsx',
        '..ts',
        '.native.ts',
        '..tsx',
        '.native.tsx' ],
     alias:
      { mobile: '/home/igor/www/megaplan/front/src/mobile',
        src: '/home/igor/www/megaplan/front/src/web' } },
  optimization:
   { minimize: false,
     minimizer: [ [TerserPlugin] ],
     namedModules: true,
     concatenateModules: true },
  target: 'webworker',
  stats: { children: false },
  resolveLoader:
   { alias:
      { 'svg-inline': 'svg-inline-loader',
        'extract-globalize-formatters-loader':
         '/home/igor/www/megaplan/front/.build/extensions/extract-globalize-formatters-loader/index.js' } } }
`

**Comment by isuhar** [comment]
This was a problem

`config = merge.strategy({
                "module.rules": "replace",
                "stats": "replace"
            })(
                config,
                resolver(options)
            )`

Must be

`
Object.assign(config, merge.strategy({
                "module.rules": "replace",
                "stats": "replace"
            })(
                config,
                resolver(options)
            ))
`

**Comment by zamotany** [comment]
@isuhar Ah, yes, in `transform` you can either mutate the `config` like `config.plugins.push(...)` or create a new instance of modified config and return it, so in you case it would be:
```js
transform({ config }) {
  // ...
  config = merge.strategy({ "module.rules": "replace", "stats": "replace" })(
    config, resolver(options)
  );
  return config;
}

```
