### ISSUE TITLE
Error setTimeout after updating RN 0.60.4

### ISSUE THREAD

**Issue by isuhar** [callstack/haul#616]
## Environment

 "react-native": "0.60.4",
"@haul-bundler/babel-preset-react-native": "0.9.0",
 "@haul-bundler/cli": "0.9.1",
"@haul-bundler/core": "0.9.1",
"@haul-bundler/preset-0.60": "0.9.0",
"jsc-android": "241213.1.0",
"@babel/core": "7.5.5",
"@babel/polyfill": "7.4.4",

**babel config:**

    module.exports = function(api) {
        api.cache.using(() => process.env.BABEL_ENV)
    
        return {
            presets: [
                "module:@haul-bundler/babel-preset-react-native",
            ],
            plugins: [
                "react-require",
                "lodash",
                "./babel-plugin-typescript-lazy-metadata",
                ["@babel/plugin-transform-runtime", {
                    helpers: true,
                    regenerator: false,
                }],
            ],
            compact: api.env("production")
        }
    }

## Description

Timing native module is not available, can't set timers.
This browser doesn't support requestAnimationFrame. Make sure that you load a polyfill in older browsers. Make sure that you load a polyfill in older browsers.

## Reproducible Demo
![image](https://user-images.githubusercontent.com/5614087/62148823-20518d00-b303-11e9-9710-2fcfdec7ec90.png)

**Comment by zamotany** [comment]
Can you tell me more when the issue is happening? Only when debugging in Chrome? Does development build w/o debugger and release build work?

**Comment by isuhar** [comment]
The issue is happening in development build. The problem is in the setTimeout function.

**webpack config**

    {
        mode: 'development',
        context: '/home/igor/www/megaplan/front',
        devtool: false,
        entry:
       [ '/home/igor/www/megaplan/front/node_modules/react-native/Libraries/polyfills/console.js',
         '/home/igor/www/megaplan/front/node_modules/react-native/Libraries/polyfills/error-guard.js',
         '/home/igor/www/megaplan/front/node_modules/react-native/Libraries/polyfills/Object.es7.js',
         '/home/igor/www/megaplan/front/node_modules/react-native/Libraries/Core/InitializeCore.js',
         './src/mobile/index' ],
      output:
       { path: '/tmp/haul-start-neilu6',
         publicPath: 'http://localhost:8081/',
         globalObject: 'this',
         filename: 'index.android.bundle' },
      module:
       { rules: [
                   {
                      "parser":{
                         "requireEnsure":false
                      }
                   },
                   {
                      "test": /\.[jt]sx?$/,
                      "exclude": /node_modules(?!.*[\/\\](react|@react-navigation|@react-native-community|@expo|pretty-format|@haul-bundler|metro))/,
                      "use":[
                         {
                            "loader":"/home/igor/www/megaplan/front/node_modules/babel-loader/lib/index.js",
                            "options":{
                               "extends":"/home/igor/www/megaplan/front/.build/babel/mobile.babel.config.js",
                               "plugins":[
                                  "/home/igor/www/megaplan/front/node_modules/@haul-bundler/core/build/utils/fixRequireIssues.js"
                               ],
                               "cacheDirectory":false
                            }
                         }
                      ]
                   },
                   {
                      "test": _core.AssetResolver.test,
                      "use":{
                         "loader":"/home/igor/www/megaplan/front/node_modules/@haul-bundler/core/build/webpack/loaders/assetLoader",
                         "options":{
                            "platform":"android",
                            "root":"/home/igor/www/megaplan/front",
                            "runtime":{
                               "logger":{
                                  "logAsJson":false,
                                  "minLoggingLevel":"info"
                               }
                            }
                         }
                      }
                   },
                   {
                      "test": /\.tsx?$/,
                      "include":"/home/igor/www/megaplan/front/src",
                      "exclude":"/node_modules/",
                      "use":[
                         {
                            "loader":"cache-loader",
                            "options":{
                               "cacheDirectory":"/tmp/webpack-cache",
                               "cacheIdentifier":"8161b72d807910c84e1f90e46246a970f333cbf6385f18745ecbc402eb017076"
                            }
                         },
                         {
                            "loader":"thread-loader",
                            "options":{
                               "workers":3,
                               "poolRespawn":false
                            }
                         },
                         {
                            "loader":"babel-loader",
                            "options":{
                               "babelrc":false,
                               "configFile":"/home/igor/www/megaplan/front/.build/babel/mobile.babel.config.js"
                            }
                         },
                         {
                            "loader":"ts-loader",
                            "options":{
                               "happyPackMode":true
                            }
                         }
                      ]
                   },
                   {
                      "test": /messages\.yml/,
                      "use":[
                         "json-loader",
                         "/home/igor/www/megaplan/front/.build/extensions/intl-messages-loader/index.js",
                         "yaml-loader"
                      ]
                   }
                ],
         noParse:
          [ /google-libphonenumber\/dist\/browser\/libphonenumber\.js$/ ] },
      plugins:
       [ CaseSensitivePathsPlugin { options: {}, pathCache: {}, fsOperations: 0, primed: false },
         DefinePlugin { definitions: {"process.env":{"NODE_ENV":"\"development\""},"__DEV__":true} },
         LoaderOptionsPlugin { options: [Object] },
         SourceMapDevToolPlugin {
           sourceMapFilename: '[file].map',
           sourceMappingURLComment: '\n//# sourceMappingURL=[url]',
           moduleFilenameTemplate: '[absolute-resource-path]',
           fallbackModuleFilenameTemplate: 'webpack://[namespace]/[resourcePath]?[hash]',
           namespace: '',
           options: [Object] },
         WebpackBasicBundlePlugin { bundle: false, sourceMap: true, preloadBundles: [] },
         IgnoreWarningsPlugin { patterns: [Array] },
         DefinePlugin { definitions: [Object] },
         ProvidePlugin { definitions: [Object] },
         ForkTsCheckerWebpackPlugin {
           startAt: 0,
           computeContextPath: [Function],
           options: [Object],
           tsconfig: './tsconfig.json',
           compilerOptions: {},
           tslint: '/home/igor/www/megaplan/front/tslint.mobile.json',
           tslintAutoFix: false,
           watch: [],
           ignoreDiagnostics: [],
           ignoreLints: [],
           ignoreLintWarnings: false,
           reportFiles: [],
           logger: [Console],
           silent: false,
           async: true,
           checkSyntacticErrors: true,
           workersNumber: 1,
           memoryLimit: 2048,
           useColors: true,
           colors: [Chalk],
           formatter: [Function: defaultFormatter],
           tsconfigPath: undefined,
           tslintPath: undefined,
           watchPaths: [],
           compiler: undefined,
           started: undefined,
           elapsed: undefined,
           cancellationToken: undefined,
           isWatching: false,
           checkDone: false,
           compilationDone: false,
           diagnostics: [],
           lints: [],
           emitCallback: [Function: noopEmitCallback],
           doneCallback: [Function: doneCallback],
           typescriptPath:
            '/home/igor/www/megaplan/front/node_modules/typescript/lib/typescript.js',
           typescript: [Object],
           typescriptVersion: '3.3.3333',
           tslintVersion: '5.13.0',
           useTypescriptIncrementalApi: true,
           vue: false,
           measureTime: false },
         CollectMessagesPlugin { collector: [Collector] } ],
      resolve:
       { plugins: [ [HasteResolver], [AssetResolver] ],
         mainFields: [ 'react-native', 'browser', 'main' ],
         extensions:
          [ '..js',
            '.native.js',
            '.js',
            '.ts',
            '.tsx',
            '..ts',
            '.native.ts',
            '..tsx',
            '.native.tsx' ],
         alias:
          { mobile: '/home/igor/www/megaplan/front/src/mobile',
            src: '/home/igor/www/megaplan/front/src/web' } },
      optimization:
       { minimize: false,
         minimizer: [ [TerserPlugin] ],
         namedModules: true,
         concatenateModules: true },
      target: 'webworker',
      stats: { children: false },
      resolveLoader:{
            alias: { 'svg-inline': 'svg-inline-loader',
            'extract-globalize-formatters-loader': '/home/igor/www/megaplan/front/.build/extensions/extract-globalize-formatters-loader/index.js'
            }
        }
    }

**Comment by zamotany** [comment]
@isuhar I've tried to reproduce the issue without any luck. Usually in those cases the problem is caused by something specific to the project, so it's hard for me to figure out the root cause. However, here are the things that you can do:
1. Create a repository with repro project
2. Get the generated bundle (for example when running development server: `curl http://localhost:8081/index.bundle?platform=<platform>`), find where `Timing native module is not available, can't set timers.` message is located, check why it's printed and just analyse the code to the point where the times should be set (probably they are not set or incorrectly set).

**Comment by isuhar** [comment]
undefined is not an object (evaluating 'Timing.createTimer')
@zamotany 
My bundle does not have a native module Timing =((

     /node_modules/react-native/Libraries/Core/Timers/JSTimers.js

     const {Timing} = require('../../BatchedBridge/NativeModules');
     Timing.createTimer(id, duration || 0, Date.now(), /* recurring */ false);

**Comment by isuhar** [comment]
but in exported variable it is
![image](https://user-images.githubusercontent.com/5614087/62294757-5febb680-b474-11e9-822e-912a21ccc056.png)

**Comment by zamotany** [comment]
@isuhar 
Can you copy & paste the code __from the bundle__ (the raw code, without any source maps etc) of those modules (including the wrapping function - the one with `__webpack_require__` argument):
- `node_modules/react-native/Libraries/Core/Timers/JSTimers.js`
- `node_modules/react-native/Libraries/BatchedBridge/NativeModules.js`

**Comment by isuhar** [comment]
@zamotany 
The raw code from http://localhost:8081/index.android.bundle

[JSTimers.txt](https://github.com/callstack/haul/files/3460514/JSTimers.txt)
[NativeModules.txt](https://github.com/callstack/haul/files/3460515/NativeModules.txt)

**Comment by zamotany** [comment]
@isuhar Does the issue happen if you use `metro-react-native-babel-preset` in `babel.config.js`??

**Comment by isuhar** [comment]
@zamotany yes, with "module:@haul-bundler/babel-preset-react-native" was some error

    module.exports = function(api) {
        api.cache.using(() => process.env.BABEL_ENV)
    
        return {
            presets: [
                "module:metro-react-native-babel-preset",
            ],
            plugins: [
                "react-require",
                "lodash",
                "./babel-plugin-typescript-lazy-metadata",
                ["@babel/plugin-transform-runtime", {
                    helpers: true,
                    regenerator: false,
                }],
            ],
            compact: api.env("production")
        }
    }

**Comment by zamotany** [comment]
@isuhar Is it possible for you to prepare a repro project? I'm running out of ideas what might be causing that and without a project where we can reproduce the issue I'm unable to help.

**Comment by isuhar** [comment]
@zamotany thank you, here is a repro project https://github.com/isuhar/haul-test-0.60.4

**Comment by zamotany** [comment]
@isuhar awesome! I'll take a look

**Comment by zamotany** [comment]
@isuhar I did some investigation and this is not an issue with Haul itself, but the config this project is using - more specifically:
```js
new ProvidePlugin({
  "Promise": "bluebird",
})
```
in `.build/envs/module.js` is causing some modification/altering in the bundle, which make global variables set on `global` invalid. For example `global.nativeModuleProxy` which is needed for exposing `NativeModules` to JS (including `Timing` native module) when `bluebird` is _provided_  makes `global.nativeModuleProxy` equal to `{}` as if no native modules were available.

**Comment by isuhar** [comment]
@zamotany thank you!
