### ISSUE TITLE
Rebuild does not work correctly

### ISSUE THREAD

**Issue by isuhar** [callstack/haul#643]
## Environment

    "react-native": "0.60.5",
    "@haul-bundler/babel-preset-react-native": "0.13.0",
    "@haul-bundler/cli": "0.13.0",
    "@haul-bundler/core": "0.13.0",
    "@haul-bundler/preset-0.60": "0.13.0",

node --stack_size=5000 --max-old-space-size=8192 "./node_modules/@haul-bundler/cli/bin/haul" "start"

## Description

After making changes to the code, the assembly is restarted, but progress is not displayed (always 100%), and a fatal error also falls from memory.

We replace webpack config and loaders.

        {
            context: options.frontDir,
            output: {
                filename: `index.${options.platform}.bundle`
            },
            resolveLoader: {
                alias: {
                    "svg-inline": "svg-inline-loader",
                    "extract-globalize-formatters-loader": require.resolve("../extensions/extract-globalize-formatters-loader")
                }
            },
            resolve: {
                extensions: [
                    '.ts',
                    '.tsx',
                    `.${options.platform}.ts`,
                    '.native.ts',
                    `.${options.platform}.tsx`,
                    '.native.tsx',
                ],
                alias: {
                    "mobile":  path.join(options.srcDir, "mobile"),
                    "src":  path.join(options.srcDir, "web")
                },
            },
           module: {
            rules:[
                {parser: {requireEnsure: false}},
                {
                    test: /\.js$/,
                    exclude: /node_modules(?!.*[\/\\](react|@react-navigation|@react-native-community|@expo|pretty-format|@haul-bundler|metro))/,
                    use: filterEmpty([
                        cacheLoader(options),
                        threadLoader(options),
                        babelLoader(options)
                    ]),
                },
                {
                    test: /\.tsx?$/,
                    include: /node_modules/,
                    use: filterEmpty([
                        cacheLoader(options),
                        threadLoader(options),
                        babelLoader(options),
                        typescriptLoader(options)
                    ]),
                },
                {
                    test: _core.AssetResolver.test,
                    use: {
                        /**
                         * Asset loader enables asset management based on image scale
                         * This needs the AssetResolver plugin in resolver.plugins to work
                         */
                        loader: _core.ASSET_LOADER_PATH,
                        options: {
                            platform: options.platform,
                            root: options.root,
                            bundle: options.bundle,
                            runtime: options.runtime,
                        }
                    }
                }
            ]
        },
            plugins: [
                new IgnoreWarningsPlugin({
                    patterns: [
                        /export '.*'( \((reex|im)ported as '.*'\))? was not found in/,
                        "Conflicting order between"
                    ]
                }),
                new DefinePlugin({
                    "process.env.REACT_NATIVE": true,
                }),
                // new ProvidePlugin({
                //     "Promise": "bluebird",
                // }),
            ],
            stats: {
                children: false,
            }
        },

![image](https://user-images.githubusercontent.com/5614087/65234276-ef106480-dadc-11e9-9561-b0f9141acf54.png)

**Comment by zamotany** [comment]
@isuhar Do you use Indexed RAM bundle or a regular bundle? Also how many modules in a project do you have (approximately)??

**Comment by isuhar** [comment]
@zamotany regular bundle, more than 250 modules, 100 screens

**Comment by zamotany** [comment]
@isuhar
What version of Node are you using?
Are you use --stack_size is correct? From the docs it should be --stack-trace-limit.

**Comment by isuhar** [comment]
Loaders:

                {
                    test: /\.js$/,
                    exclude: /node_modules(?!.*[\/\\](react|@react-navigation|@react-native-community|@expo|pretty-format|@haul-bundler|metro))/,
                    use: filterEmpty([
                        cacheLoader(options),
                        threadLoader(options),
                        babelLoader(options)
                    ]),
                },
                {
                    test: /\.tsx?$/,
                    include: /node_modules/,
                    use: filterEmpty([
                        cacheLoader(options),
                        threadLoader(options),
                        babelLoader(options),
                        typescriptLoader(options)
                    ]),
                },
                {
                    test: /\.tsx?$/,
                    include: options.srcDir,
                    exclude: "/node_modules/",
                    use: filterEmpty([
                        cacheLoader(options),
                        threadLoader(options),
                        babelLoader(options),
                        typescriptLoader(options)
                    ])
                },

**Comment by isuhar** [comment]
@zamotany with --stack-trace-limit some error =(

**Comment by zamotany** [comment]
@isuhar Honestly I'm still not sure why the issue is happening or even if it's connected with Haul at all. But I've noticed you're transpiling all of the `node_modules` here:
```js
{
                test: /\.tsx?$/,
                include: /node_modules/,
                use: filterEmpty([
                    cacheLoader(options),
                    threadLoader(options),
                    babelLoader(options),
                    typescriptLoader(options)
                ]),
            },
```
Maybe you should transpile only the modules that need transpiling instead of every module and let me know if that solves your issue?

**Comment by isuhar** [comment]
After upgrading node from 10 to 12, it worked
