### ISSUE TITLE
eliminate need for react-native symlink in monorepo

### ISSUE THREAD

**Issue by matthargett** [callstack/haul#667]
## Environment

monorepo using yarn workspaces 

## Description

We currently need to make a react-native symlink in a monorepo's sub-package  to the hoisted version in the monorepo root. This is one of the issues for the reproduction example we gave with #474.

## Reproducible Demo

See example we provided for #474.

**Comment by zamotany** [comment]
Temporary workaround is to specify `root` option in `withPolyfills`:
```js
import { withPolyfills, makeConfig } from '@haul-bundler/preset-0.59';
import { resolve } from 'path';

export default makeConfig({
  bundles: {
    index: {
      entry: withPolyfills('./index', { root: resolve(__dirname, '../..') }),
    },
  },
});
```

**Comment by zamotany** [comment]
Fixed in:
- @haul-bundler/cli@0.14.2
- @haul-bundler/core@0.14.2
