### ISSUE TITLE
App does not reload, can't see "Live Reloading" option

### ISSUE THREAD

**Issue by ptgamr** [callstack/haul#682]
## Environment

react-native@0.61.4
@haul-bundler/cli@0.15.0

App run via `npx react-native run-android` in an Android emulator.

## Description

Brand new react native project, app does not reload as I change the source file  and I can't see **Live Reloading** option.

I saw **Enable/Disable Fast Refresh**  instead, and toggling this on/off doesn't make any difference.

![2019-11-26_12:46:48](https://user-images.githubusercontent.com/1619740/69587601-daa39780-104a-11ea-89a9-6a50be12f2f6.png)

As I understand, Fast Refresh isn't supported yet: https://github.com/callstack/haul/issues/583

I'm not too sure this is a bug, I might have missed something.

**Comment by zamotany** [comment]
Live Reload was removed in favour of Fast Refresh, which we doesn't support yet. There's no Live Reload option anymore.

**Comment by ptgamr** [comment]
@zamotany thanks for the info. I think this should be included in the docs as I think others might have the same question... I tried out Haul today and really glad that symlink did work... but Live Reload is kind of an essentials feature for me while developing. Do you have an idea when Fast Refresh will be supported?

**Comment by zamotany** [comment]
Hard to tell, it really depends on how difficult will be to integrate https://github.com/pmmmwh/react-refresh-webpack-plugin with Haul - more specifically with React Native environment. I already know, that some code will need to be rewritten in `react-refresh-webpack-plugin`, since it assumes there's a global `window` variable.

**Comment by zamotany** [comment]
If you want, you can try integrating that into your project. For a quick workaround for `window` you can use `BannerPlugin` with something like this, to expose `window` variable:
```js
this.window = this;
```
