### ISSUE TITLE
Impossible to add loaders before babelWorkerLoader: Module build failed ENOENT

### ISSUE THREAD

**Issue by hedgepigdaniel** [callstack/haul#700]
## Environment

Haul versions after https://github.com/callstack/haul/pull/689 including 0.17.0 

## Description

It is not possible to insert a webpack loader before the new `babelWorkerLoader`. Doing so results in an error because the `babelWorkerLoader` `worker` attempts to open a file such as `node_modules/eslint-loader/index.js??ref--7!node_modules/source-map-loader/index.js!/home/daniel/code/ol/ol-docker/engine/OpenLearningClient/src/native/index.android.js` (which is not a file path, rather a webpack loader request string).

The problem occurs because Haul's new default `babelWorkerLoader` [exports](https://github.com/callstack/haul/blob/7baa8aa57ef41eb4bc3d2382d2f176ddc4a5f505/packages/haul-core/src/webpack/loaders/babelWorkerLoader/babelWorkerLoader.ts#L37) a [pitching webpack loader](https://webpack.js.org/api/loaders/#pitching-loader), but the first argument is:
- (in fact) a webpack loader request string for the request to be loaded to create the imput for the loader (called `remainingRequest` in the example on the webpack docs)
- [named `source`](https://github.com/callstack/haul/blob/7baa8aa57ef41eb4bc3d2382d2f176ddc4a5f505/packages/haul-core/src/webpack/loaders/babelWorkerLoader/babelWorkerLoader.ts#L12) in `babelWorkerLoader`
- [Treated as a file path](https://github.com/callstack/haul/blob/7baa8aa57ef41eb4bc3d2382d2f176ddc4a5f505/packages/haul-core/src/webpack/loaders/babelWorkerLoader/worker.ts#L35) in `babelWorkerLoader` 

## Reproducible Demo

(Not a working demo, but enough to understand the problem):

```javascript
/// haul.config.js
import { makeConfig, withPolyfills } from '@haul-bundler/preset-0.59';

export default makeConfig({
  bundles: {
    index: {
      entry: withPolyfills(`./src/native/index`),
      transform: ({ env, config }) => {
        config.module.rules.push({
          // This is needed for debugging from VSCode
          // See: https://github.com/callstack/haul/blob/master/docs/Recipes.md#debugging-with-react-native-tools-vscode-react-native
          test: /\.[j|t]sx?$/,
          use: 'source-map-loader',
          enforce: 'pre',
        });
      },
    },
  },
});
```

```
$ yarn run haul bundle --platform android
$ error ▶︎ ./src/native/index.android.js
Module build failed (from ./node_modules/@haul-bundler/core/build/webpack/loaders/babelWorkerLoader/index.js):
Error: ENOENT: no such file or directory, open '/home/daniel/code/ol/ol-docker/engine/OpenLearningClient/node_modules/eslint-loader/index.js??ref--7!/home/daniel/code/ol/ol-docker/engine/OpenLearningClient/node_modules/source-map-loader/index.js!/home/daniel/code/ol/ol-docker/engine/OpenLearningClient/src/native/index.android.js'
    at Object.openSync (fs.js:457:3)
    at Object.readFileSync (fs.js:359:35)
    at Object.process (/home/daniel/code/ol/ol-docker/engine/OpenLearningClient/node_modules/@haul-bundler/core/build/webpack/loaders/babelWorkerLoader/worker.js:34:30)
    at execFunction (/home/daniel/code/ol/ol-docker/engine/OpenLearningClient/node_modules/@haul-bundler/core/node_modules/jest-worker/build/workers/threadChild.js:196:17)
    at execHelper (/home/daniel/code/ol/ol-docker/engine/OpenLearningClient/node_modules/@haul-bundler/core/node_modules/jest-worker/build/workers/threadChild.js:180:5)
    at execMethod (/home/daniel/code/ol/ol-docker/engine/OpenLearningClient/node_modules/@haul-bundler/core/node_modules/jest-worker/build/workers/threadChild.js:184:5)
    at MessagePort.messageListener (/home/daniel/code/ol/ol-docker/engine/OpenLearningClient/node_modules/@haul-bundler/core/node_modules/jest-worker/build/workers/threadChild.js:99:7)
    at MessagePort.emit (events.js:321:20)
    at MessagePort.onmessage (internal/worker/io.js:78:8)
 @ multi ./node_modules/@haul-bundler/preset-0.59/vendor/polyfills/Object.es6.js ./node_modules/@haul-bundler/preset-0.59/vendor/polyfills/console.js ./node_modules/@haul-bundler/preset-0.59/vendor/polyfills/error-guard.js ./node_modules/@haul-bundler/preset-0.59/vendor/polyfills/Number.es6.js ./node_modules/@haul-bundler/preset-0.59/vendor/polyfills/String.prototype.es6.js ./node_modules/@haul-bundler/preset-0.59/vendor/polyfills/Array.prototype.es6.js ./node_modules/@haul-bundler/preset-0.59/vendor/polyfills/Array.es6.js ./node_modules/@haul-bundler/preset-0.59/vendor/polyfills/Object.es7.js react-native/Libraries/Core/InitializeCore.js ./src/native/index main[9]
./node_modules/@haul-bundler/preset-0.59/vendor/polyfills/Array.es6.js
```

## Workaround
Customise the webpack configuration to replace `babelWorkerLoader` with `babel-loader`.

**Comment by Natteke** [comment]
I faced the same issue and just:
`config.module.rules[1] = {
        test: /\.[jt]sx?$/,
        loader: 'babel-loader',
};`

it helped, but... 
any suggestions of better solutions?

**Comment by karon-hyppolite** [comment]
Hello.
How did you solve this issue?
