### ISSUE TITLE
Shared components with monorepo

### ISSUE THREAD

**Issue by Natteke** [callstack/haul#706]
Hi!
Can you suggest any solutions for this?
I'm trying to build 2 react-native apps with shared codebase and stuck on components import.

If i import any jsx, this happens
![image](https://user-images.githubusercontent.com/24633723/75348172-595ed980-58b3-11ea-9421-efc98bbb5f61.png)
![image](https://user-images.githubusercontent.com/24633723/75348323-a5aa1980-58b3-11ea-97b6-fcc30077aac6.png)

But if there is no jsx, it works...

![image](https://user-images.githubusercontent.com/24633723/75348385-c6726f00-58b3-11ea-8abf-8f63bf3fa754.png)
![image](https://user-images.githubusercontent.com/24633723/75348351-b5296280-58b3-11ea-9d4e-c2cf726f7bd7.png)
![image](https://user-images.githubusercontent.com/24633723/75348639-48fb2e80-58b4-11ea-8480-fb4594232523.png)

I assume that the problem lies in babel/jsx/compiling process...

ENV
"@haul-bundler/core": "^0.17.0",
"@haul-bundler/cli": "^0.17.0",
"react-native": "0.61.5",

**Comment by Natteke** [comment]
This is not a haul issue, but RN.
solved here: https://github.com/facebook/react-native/issues/26687#issuecomment-537504575

**Comment by zamotany** [comment]
It's very odd to be importing a module from different package in monorepo with relative path that goes outside of the RN app package. I suggest to setup your project in a way that treats `shared` as a dependency and you import it like a `node_module` dependency.

**Comment by Natteke** [comment]
@zamotany you right. Moreover you should import all your native elements from the single point, because they all connected through the react-native bridge. I forgot about that.

This is not an issue at all, just my misunderstanding of how RN works.
