### ISSUE TITLE
Can't get template to compile and run

### ISSUE THREAD

**Issue by ScottPierce** [callstack/haul#709]
## Environment
Node.js v13.10.1
MacOS Catalina

`package.json`:
```
{
  "name": "BehindTheWheel",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "haul": "haul"
  },
  "dependencies": {
    "react": "16.9.0",
    "react-dom": "^16.13.0",
    "react-hot-loader": "^4.12.19",
    "react-native": "0.61.5"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@haul-bundler/cli": "^0.18.0",
    "@haul-bundler/preset-0.60": "^0.18.0",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "haul": "^1.0.0-rc.15",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

My `haul.config.js`
```
import { createWebpackConfig } from "haul";
import { makeConfig, withPolyfills } from "@haul-bundler/preset-0.60";

export default {
  webpack: createWebpackConfig(({ platform }) => ({
    entry: withPolyfills('./index.js')
  }))
};

```

## Description
All I did was follow the instructions in the haul readme to try and build a template, and I've seen a rotating line of issues, many of which seem to be referenced by this closed ticket: https://github.com/callstack/haul/issues/535

I'm now seeing an issue that I can't seem to find a fix for, I'm not sure how to proceed.
![Screenshot_1584074617](https://user-images.githubusercontent.com/871169/76590507-b073c980-64c3-11ea-8fc2-b78819bd5fb8.png)

## Reproducible Demo

I basically used npx to create a react template, and then installed haul on top of it via yarn, just like the readme suggests. I've seen issue after issue though.

**Comment by zamotany** [comment]
Do not use `haul` package - it was deprecated not not supported a log time ago. Use `@haul-bundler/cli` to `init` a new project. Check the getting started guide here: https://github.com/callstack/haul#getting-started

Am going to close this issue, If you have any problems feel free to reopen it.

**Comment by ScottPierce** [comment]
@zamotany How do I use `@haul-bundler/cli` to init? I'm just following the documentation.

**Comment by zamotany** [comment]
`yarn add -D @haul-bundler/cli` or `npm install` it then run `yarn haul init` or npx haul init`
