### ISSUE TITLE
`node_modules_local` folder is not respected

### ISSUE THREAD

**Issue by ScottPierce** [callstack/haul#711]
## Description
I'm using Kotlin to compile a react-native application to javascript. Currently, the application is outputting several javascript files/libs to a folder in the react-native project folder.

The compiled js files find the other files/libs that it outputs by using common js, i.e. `require('<lib name>)'`. I was solving this with metro, by adding local modules in the `node_modules_local` folder, via something that looks like this:

`./node_modules_local/kotlin/package.json`
```
{
  "main": "../../lib/kotlin.js",
  "name": "kotlin",
  "version": "1.0.0"
}
```

It appears though that haul is only looking for modules inside of the `node_modules` folder, and by copying that local module there, it works.

**Is this a bug, or is there a way that I should be telling webpack to look in that folder for modules as well?**

**Comment by zamotany** [comment]
It's a Webpack thing. You need to tell webpack where your modules will be: https://webpack.js.org/configuration/resolve/#resolvemodules

Use `transform` function in `haul.config.js` to modify webpack config.
