### ISSUE TITLE
Add script to build process during init

### ISSUE THREAD

**Issue by satya164** [callstack/haul#87]
Should replace React Native's packager CLI in gradle and xcode scripts with haul during init.

- [x] iOS ~ @grabbou
- [ ] Android ~ @satya164

**Comment by grabbou** [comment]
There's a problem on first Xcode run as `haul-integrate.sh` will be executed after React own build scripts are executed. That means the very first run will launch packager no matter what we do. Second works properly. Figure out how to fix it. 

We might need to run `haul-integrate.sh` during `init` command to make the first change. The purpose of it to sit in `build script` is to avoid updates of React / npm installs.

**Comment by grabbou** [comment]
Now that we have ENV variables, we will be removing this legacy workaround. See #234 for details.
